In [25]:
import glob
import random

In [27]:

ps = glob.glob('/home/abhijit/Jyotirmay/thesis/hquicknat/datasets/KORA/processed_data_all_/data/*')

vols = []
for p in ps:
    vid = p.split('/')[-1].split('.')[0]
    vols.append(vid)
    print(vid)
    
random.shuffle(vols)

l  = len(vols)
t = int(l*0.8)
print(l, t)
train = vols[:t]
val = vols[t:]

for v in train:
    print(v)

print('...................................................................')

for vv in val:
    print(vv)
    

KORA2458197
KORA2452941
KORA2462345
KORA2460145
KORA2460824
KORA2459134
KORA2460408
KORA2459983
KORA2460326
KORA2455792
KORA2460354
KORA2452687
KORA2460813
KORA2459431
KORA2453048
KORA2456004
KORA2452094
KORA2459807
KORA2452930
KORA2453009
KORA2459310
KORA2459365
KORA2452338
KORA2452146
KORA2452902
KORA2455852
KORA2458096
KORA2452978
KORA2453306
KORA2461061
KORA2459908
KORA2461190
KORA2460270
KORA2462328
KORA2460436
KORA2460889
KORA2453328
KORA2452924
KORA2453251
KORA2452118
KORA2452036
KORA2453352
KORA2453363
KORA2459745
KORA2455572
KORA2453015
KORA2455375
KORA2452471
KORA2459947
KORA2460348
KORA2457044
KORA2459961
KORA2459376
KORA2452604
KORA2452577
KORA2460734
KORA2453082
KORA2452913
KORA2459605
KORA2458402
KORA2460867
KORA2452995
KORA2455764
KORA2459681
KORA2460253
KORA2456230
KORA2452698
KORA2452353
KORA2458068
KORA2453844
KORA2456535
KORA2457401
KORA2458169
KORA2452786
KORA2460565
KORA2458040
KORA2460227
KORA2458314
KORA2454788
KORA2460315
KORA2406152
KORA2455615
KORA2453464
KORA

In [ ]:
data_dir = "/home/abhijit/nas_drive/Data_WholeBody/KORA/KORA_all/KORA_Nifti"
label_dir = "/home/abhijit/nas_drive/Data_WholeBody/KORA/KORA_segs/ROI_liver_spleen_Daniel"
orientation = 'KORA_AXI'
modality = 1

In [ ]:
def load_file_paths(data_dir, label_dir, volumes_txt_file=None, modality='1'):
    """
    This function returns the file paths combined as a list where each element is a 2 element tuple, 0th being data and 1st being label.
    It should be modified to suit the need of the project
    :param data_dir: Directory which contains the data files
    :param label_dir: Directory which contains the label files
    :param volumes_txt_file: (Optional) Path to the a csv file, when provided only these data points will be read
    :return: list of file paths as string
    """
    global final_exclusion_list
    modality_map = {
        '1': 'opp_8',
        '2': '[F_1|W_3]',
        '4': '[F_1|W_3|opp_8|in_6]'
    }

    if volumes_txt_file:
        with open(volumes_txt_file) as file_handle:
            volumes_to_use = file_handle.read().splitlines()
    else:
        volumes_to_use = [name for name in os.listdir(data_dir)]

    for vol in volumes_to_use:
        # if vol not in final_exclusion_list:
        try:
            # for UKB
            # file = glob.glob(os.path.join(data_dir, vol, pick_file[vol]))
            # file selector for Kora.
            file = glob.glob(os.path.join(data_dir, vol, '*{}.nii.gz'.format(modality_map[modality])))
            print(file)
            if len(file) is not 0:
                # For KORA
                file_paths.append([file[0], os.path.join(label_dir, vol, "comp_mask.nii")])
            else:
                zero_file.append(vol)
        except Exception as e:
            new_excluded.append(vol)
            print(e)
            continue

    return file_paths

In [ ]:
!pwd

In [18]:
import os
import torch
from selenium import webdriver
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.by import By


class CommonUtils(object):
    def __init__(self):
        super().__init__()
        self.elem1 = None

    @staticmethod
    def create_if_not(path):
        """
        Creates a folder at the given path if one doesnt exist before
        ===

        :param path: destination to check for existense
        :return: None
        """
        if not os.path.exists(path):
            os.makedirs(path)

    @staticmethod
    def reparameterize(mu, logvar):
        """

        :param mu: mean
        :param logvar: variance
        :return: randomly generated sample
        """
        std = torch.exp(0.5 * logvar)
        eps = torch.randn_like(std)
        return mu + eps * std

    def setup_whatsapp_notifier(self, driver_path='/home/abhijit/Jyotirmay/thesis/hquicknat/utils/chromedriver', receiver="Tum Madhu Mathematics"):
        driver = webdriver.Chrome(driver_path)
        driver.get('https://web.whatsapp.com')
        input('click "enter" once whatsapp configured in selenium invoked browser!')
        print("Success!!!")
        spans = driver.find_elements_by_tag_name('span')
        elem_lst = [x for x in spans if x.get_attribute('title') == 'Tum Madhu Mathematics']
        elem = elem_lst[0]
        elem.click()
        self.elem1 = driver.find_element_by_class_name('_3u328')

    def whatsapp_notifier(self, message):
        self.elem1.send_keys(message + '\r', Keys.RETURN)
        print('Notified in whatsapp')

In [19]:
util = CommonUtils()
util.setup_whatsapp_notifier()

click "enter" once whatsapp configured in selenium invoked browser!
Success!!!
<selenium.webdriver.remote.webelement.WebElement (session="85753f61e92210eaaabf91328d877e01", element="56fd59d3-de4e-4449-99ef-0cb98500f47e")>


In [20]:
util.whatsapp_notifier('f f')

Notified in whatsapp


In [38]:
import numpy as np

a = np.reshape(np.arange(27), (3,3,3))
b = (a>10).astype('int')
c = (a>12).astype('int')
print(a, b, c)

x = [b, c]

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]] [[[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]] [[[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]]


In [32]:
def intersection_overlap_per_structure(samples):
    iou_s = []
    for c in range(2):
        if c == 0:
            continue
        inter = (samples[0] == c).astype('int')
        union = (samples[0] == c).astype('int')
        for s in range(1, 2):
            nxt = (samples[s] == c).astype('int')
            inter = np.multiply(inter, nxt)
            union = (np.add(union, nxt) > 0).astype('int')
        s_inter, s_union = np.sum(inter), np.sum(union) + 0.0001
        iou_s.append(np.divide(s_inter, s_union))
    return iou_s

In [39]:
print(x)

[array([[[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 1],
        [1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]]]), array([[[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]]])]


In [40]:
o = intersection_overlap_per_structure(x)

In [41]:
print(o)

[0.8749945312841795]


In [42]:
14/16

0.875

In [49]:
x = torch.tensor([[1., -1.], [1., 0.]])

In [50]:

i = x
n = x.sqrt()
j = x.exp()
k = x.exp().pow(2)
l = x.exp().pow(2).log()

print(i,n, j, k,l)

tensor([[ 1., -1.],
        [ 1.,  0.]]) tensor([[1., nan],
        [1., 0.]]) tensor([[2.7183, 0.3679],
        [2.7183, 1.0000]]) tensor([[7.3891, 0.1353],
        [7.3891, 1.0000]]) tensor([[ 2.0000, -2.0000],
        [ 2.0000,  0.0000]])


In [53]:
from medpy.metric import jc

In [54]:
#!pip install medpy

In [63]:
b = jc(np.array([0,0]), np.array([0,0]))
print(b)

ZeroDivisionError: float division by zero

In [70]:
ps = glob.glob('/home/abhijit/Jyotirmay/thesis/hquicknat/datasets/KORA/processed_data/labels/**')
print(ps)

['/home/abhijit/Jyotirmay/thesis/hquicknat/datasets/KORA/processed_data/labels/KORA2458197.nii.gz', '/home/abhijit/Jyotirmay/thesis/hquicknat/datasets/KORA/processed_data/labels/KORA2452941.nii.gz', '/home/abhijit/Jyotirmay/thesis/hquicknat/datasets/KORA/processed_data/labels/KORA2462345.nii.gz', '/home/abhijit/Jyotirmay/thesis/hquicknat/datasets/KORA/processed_data/labels/KORA2460145.nii.gz', '/home/abhijit/Jyotirmay/thesis/hquicknat/datasets/KORA/processed_data/labels/KORA2460824.nii.gz', '/home/abhijit/Jyotirmay/thesis/hquicknat/datasets/KORA/processed_data/labels/KORA2459134.nii.gz', '/home/abhijit/Jyotirmay/thesis/hquicknat/datasets/KORA/processed_data/labels/KORA2460408.nii.gz', '/home/abhijit/Jyotirmay/thesis/hquicknat/datasets/KORA/processed_data/labels/KORA2459983.nii.gz', '/home/abhijit/Jyotirmay/thesis/hquicknat/datasets/KORA/processed_data/labels/KORA2460326.nii.gz', '/home/abhijit/Jyotirmay/thesis/hquicknat/datasets/KORA/processed_data/labels/KORA2455792.nii.gz', '/home/ab

In [71]:
lbl = ps[0]

import nibabel as nb

data = nb.load(lbl).get_fdata()

print(data.shape)

(34, 256, 176)


In [84]:
def intersection_overlap_per_structure(samples):
    iou_s = []
    for c in range(3):
        if c == 0:
            continue
        inter = (samples[0] == c).astype('int')
        union = (samples[0] == c).astype('int')
        for s in range(1, 2):
            nxt = (samples[s] == c).astype('int')
            inter = np.multiply(inter, nxt)
            union = (np.add(union, nxt) > 0).astype('int')
        s_inter, s_union = np.sum(inter), np.sum(union) + 0.0001
        iou_s.append(np.divide(s_inter, s_union))
    return iou_s

def find_very_similar_labelmaps(threshold=0.99):
    ps = glob.glob('/home/abhijit/Jyotirmay/thesis/hquicknat/datasets/KORA/processed_data/labels/**')
    samples = {}
    for p in ps:
        volid = p.split('/')[-1].split('.')[0]
        samples[volid] = nb.load(p).get_fdata()

    for s1 in samples.keys():
        for s2 in samples.keys():
            print(samples[s1].shape,samples[s2].shape)
            if s1 == s2 or samples[s1].shape != samples[s2].shape:
                continue
            iou = intersection_overlap_per_structure([samples[s1], samples[s2]])
            print(iou)
            if np.mean(iou)>threshold:
                print(s1, s2)

find_very_similar_labelmaps()

(29, 256, 176) (29, 256, 176)
(29, 256, 176) (31, 256, 176)
(29, 256, 176) (32, 256, 176)
(29, 256, 176) (26, 256, 176)
(29, 256, 176) (33, 256, 176)
(29, 256, 176) (33, 256, 176)
(29, 256, 176) (42, 256, 176)
(29, 256, 176) (28, 256, 176)
(29, 256, 176) (30, 256, 176)
(29, 256, 176) (26, 256, 176)
(29, 256, 176) (37, 256, 176)
(29, 256, 176) (24, 256, 176)
(29, 256, 176) (40, 256, 176)
(29, 256, 176) (28, 256, 176)
(29, 256, 176) (30, 256, 176)
(29, 256, 176) (39, 256, 176)
(29, 256, 176) (27, 256, 176)
(29, 256, 176) (34, 256, 176)
(29, 256, 176) (28, 256, 176)
(29, 256, 176) (36, 256, 176)
(29, 256, 176) (32, 256, 176)
(29, 256, 176) (31, 256, 176)
(29, 256, 176) (27, 256, 176)
(29, 256, 176) (34, 256, 176)
(29, 256, 176) (29, 256, 176)
[0.2228712531563316, 0.5059594121205526]
(29, 256, 176) (36, 256, 176)
(29, 256, 176) (29, 256, 176)
[0.3022049878435719, 0.5171983467057392]
(29, 256, 176) (32, 256, 176)
(29, 256, 176) (31, 256, 176)
(29, 256, 176) (28, 256, 176)
(29, 256, 176) (28

[0.2913485395505713, 0.5398136900092835]
(31, 256, 176) (32, 256, 176)
(31, 256, 176) (27, 256, 176)
(31, 256, 176) (31, 256, 176)
[0.28394034648006444, 0.46976652523187573]
(31, 256, 176) (33, 256, 176)
(31, 256, 176) (31, 256, 176)
[0.31895732066364474, 0.5566667600485798]
(31, 256, 176) (32, 256, 176)
(31, 256, 176) (35, 256, 176)
(31, 256, 176) (25, 256, 176)
(32, 256, 176) (29, 256, 176)
(32, 256, 176) (31, 256, 176)
(32, 256, 176) (32, 256, 176)
(32, 256, 176) (26, 256, 176)
(32, 256, 176) (33, 256, 176)
(32, 256, 176) (33, 256, 176)
(32, 256, 176) (42, 256, 176)
(32, 256, 176) (28, 256, 176)
(32, 256, 176) (30, 256, 176)
(32, 256, 176) (26, 256, 176)
(32, 256, 176) (37, 256, 176)
(32, 256, 176) (24, 256, 176)
(32, 256, 176) (40, 256, 176)
(32, 256, 176) (28, 256, 176)
(32, 256, 176) (30, 256, 176)
(32, 256, 176) (39, 256, 176)
(32, 256, 176) (27, 256, 176)
(32, 256, 176) (34, 256, 176)
(32, 256, 176) (28, 256, 176)
(32, 256, 176) (36, 256, 176)
(32, 256, 176) (32, 256, 176)
[0.2

[0.10941793586423973, 0.6576970212256026]
(26, 256, 176) (35, 256, 176)
(26, 256, 176) (25, 256, 176)
(26, 256, 176) (29, 256, 176)
(26, 256, 176) (35, 256, 176)
(26, 256, 176) (31, 256, 176)
(26, 256, 176) (32, 256, 176)
(26, 256, 176) (34, 256, 176)
(26, 256, 176) (32, 256, 176)
(26, 256, 176) (32, 256, 176)
(26, 256, 176) (27, 256, 176)
(26, 256, 176) (27, 256, 176)
(26, 256, 176) (29, 256, 176)
(26, 256, 176) (38, 256, 176)
(26, 256, 176) (36, 256, 176)
(26, 256, 176) (27, 256, 176)
(26, 256, 176) (30, 256, 176)
(26, 256, 176) (32, 256, 176)
(26, 256, 176) (35, 256, 176)
(26, 256, 176) (39, 256, 176)
(26, 256, 176) (38, 256, 176)
(26, 256, 176) (31, 256, 176)
(26, 256, 176) (30, 256, 176)
(26, 256, 176) (29, 256, 176)
(26, 256, 176) (39, 256, 176)
(26, 256, 176) (28, 256, 176)
(26, 256, 176) (33, 256, 176)
(26, 256, 176) (26, 256, 176)
[0.1915286271537242, 0.4282734746902742]
(26, 256, 176) (28, 256, 176)
(26, 256, 176) (36, 256, 176)
(26, 256, 176) (33, 256, 176)
(26, 256, 176) (3

[0.052089670744186495, 0.6048275610752228]
(33, 256, 176) (29, 256, 176)
(33, 256, 176) (34, 256, 176)
(33, 256, 176) (32, 256, 176)
(33, 256, 176) (24, 256, 176)
(33, 256, 176) (25, 256, 176)
(33, 256, 176) (27, 256, 176)
(33, 256, 176) (39, 256, 176)
(33, 256, 176) (26, 256, 176)
(33, 256, 176) (35, 256, 176)
(33, 256, 176) (25, 256, 176)
(33, 256, 176) (29, 256, 176)
(33, 256, 176) (35, 256, 176)
(33, 256, 176) (31, 256, 176)
(33, 256, 176) (32, 256, 176)
(33, 256, 176) (34, 256, 176)
(33, 256, 176) (32, 256, 176)
(33, 256, 176) (32, 256, 176)
(33, 256, 176) (27, 256, 176)
(33, 256, 176) (27, 256, 176)
(33, 256, 176) (29, 256, 176)
(33, 256, 176) (38, 256, 176)
(33, 256, 176) (36, 256, 176)
(33, 256, 176) (27, 256, 176)
(33, 256, 176) (30, 256, 176)
(33, 256, 176) (32, 256, 176)
(33, 256, 176) (35, 256, 176)
(33, 256, 176) (39, 256, 176)
(33, 256, 176) (38, 256, 176)
(33, 256, 176) (31, 256, 176)
(33, 256, 176) (30, 256, 176)
(33, 256, 176) (29, 256, 176)
(33, 256, 176) (39, 256, 17

[0.23529411599934094, 0.6633907427150807]
(28, 256, 176) (34, 256, 176)
(28, 256, 176) (24, 256, 176)
(28, 256, 176) (37, 256, 176)
(28, 256, 176) (30, 256, 176)
(28, 256, 176) (32, 256, 176)
(28, 256, 176) (23, 256, 176)
(28, 256, 176) (25, 256, 176)
(28, 256, 176) (29, 256, 176)
(28, 256, 176) (31, 256, 176)
(28, 256, 176) (41, 256, 176)
(28, 256, 176) (29, 256, 176)
(28, 256, 176) (25, 256, 176)
(28, 256, 176) (28, 256, 176)
[0.44257587823973854, 0.7161594302101553]
(28, 256, 176) (38, 256, 176)
(28, 256, 176) (30, 256, 176)
(28, 256, 176) (32, 256, 176)
(28, 256, 176) (31, 256, 176)
(28, 256, 176) (33, 256, 176)
(28, 256, 176) (27, 256, 176)
(28, 256, 176) (26, 256, 176)
(28, 256, 176) (29, 256, 176)
(28, 256, 176) (37, 256, 176)
(28, 256, 176) (40, 256, 176)
(28, 256, 176) (34, 256, 176)
(28, 256, 176) (40, 256, 176)
(28, 256, 176) (32, 256, 176)
(28, 256, 176) (33, 256, 176)
(28, 256, 176) (34, 256, 176)
(28, 256, 176) (23, 256, 176)
(28, 256, 176) (30, 256, 176)
(28, 256, 176) (

[0.506597746995453, 0.7573973039038051]
(26, 256, 176) (33, 256, 176)
(26, 256, 176) (33, 256, 176)
(26, 256, 176) (42, 256, 176)
(26, 256, 176) (28, 256, 176)
(26, 256, 176) (30, 256, 176)
(26, 256, 176) (26, 256, 176)
(26, 256, 176) (37, 256, 176)
(26, 256, 176) (24, 256, 176)
(26, 256, 176) (40, 256, 176)
(26, 256, 176) (28, 256, 176)
(26, 256, 176) (30, 256, 176)
(26, 256, 176) (39, 256, 176)
(26, 256, 176) (27, 256, 176)
(26, 256, 176) (34, 256, 176)
(26, 256, 176) (28, 256, 176)
(26, 256, 176) (36, 256, 176)
(26, 256, 176) (32, 256, 176)
(26, 256, 176) (31, 256, 176)
(26, 256, 176) (27, 256, 176)
(26, 256, 176) (34, 256, 176)
(26, 256, 176) (29, 256, 176)
(26, 256, 176) (36, 256, 176)
(26, 256, 176) (29, 256, 176)
(26, 256, 176) (32, 256, 176)
(26, 256, 176) (31, 256, 176)
(26, 256, 176) (28, 256, 176)
(26, 256, 176) (28, 256, 176)
(26, 256, 176) (34, 256, 176)
(26, 256, 176) (24, 256, 176)
(26, 256, 176) (37, 256, 176)
(26, 256, 176) (30, 256, 176)
(26, 256, 176) (32, 256, 176)


[0.12030685811997421, 0.2051825396325726]
(24, 256, 176) (38, 256, 176)
(24, 256, 176) (32, 256, 176)
(24, 256, 176) (24, 256, 176)
[0.1010736188567974, 0.4501965990456518]
(24, 256, 176) (38, 256, 176)
(24, 256, 176) (31, 256, 176)
(24, 256, 176) (32, 256, 176)
(24, 256, 176) (35, 256, 176)
(24, 256, 176) (27, 256, 176)
(24, 256, 176) (24, 256, 176)
[0.5478957401794456, 0.5916147420640844]
(24, 256, 176) (32, 256, 176)
(24, 256, 176) (32, 256, 176)
(24, 256, 176) (25, 256, 176)
(24, 256, 176) (23, 256, 176)
(24, 256, 176) (27, 256, 176)
(24, 256, 176) (36, 256, 176)
(24, 256, 176) (32, 256, 176)
(24, 256, 176) (34, 256, 176)
(24, 256, 176) (26, 256, 176)
(24, 256, 176) (30, 256, 176)
(24, 256, 176) (31, 256, 176)
(24, 256, 176) (32, 256, 176)
(24, 256, 176) (27, 256, 176)
(24, 256, 176) (31, 256, 176)
(24, 256, 176) (33, 256, 176)
(24, 256, 176) (31, 256, 176)
(24, 256, 176) (32, 256, 176)
(24, 256, 176) (35, 256, 176)
(24, 256, 176) (25, 256, 176)
(40, 256, 176) (29, 256, 176)
(40, 2

(28, 256, 176) (34, 256, 176)
(28, 256, 176) (32, 256, 176)
(28, 256, 176) (33, 256, 176)
(28, 256, 176) (30, 256, 176)
(28, 256, 176) (32, 256, 176)
(28, 256, 176) (24, 256, 176)
(28, 256, 176) (38, 256, 176)
(28, 256, 176) (32, 256, 176)
(28, 256, 176) (24, 256, 176)
(28, 256, 176) (38, 256, 176)
(28, 256, 176) (31, 256, 176)
(28, 256, 176) (32, 256, 176)
(28, 256, 176) (35, 256, 176)
(28, 256, 176) (27, 256, 176)
(28, 256, 176) (24, 256, 176)
(28, 256, 176) (32, 256, 176)
(28, 256, 176) (32, 256, 176)
(28, 256, 176) (25, 256, 176)
(28, 256, 176) (23, 256, 176)
(28, 256, 176) (27, 256, 176)
(28, 256, 176) (36, 256, 176)
(28, 256, 176) (32, 256, 176)
(28, 256, 176) (34, 256, 176)
(28, 256, 176) (26, 256, 176)
(28, 256, 176) (30, 256, 176)
(28, 256, 176) (31, 256, 176)
(28, 256, 176) (32, 256, 176)
(28, 256, 176) (27, 256, 176)
(28, 256, 176) (31, 256, 176)
(28, 256, 176) (33, 256, 176)
(28, 256, 176) (31, 256, 176)
(28, 256, 176) (32, 256, 176)
(28, 256, 176) (35, 256, 176)
(28, 256, 

[0.15884410013416114, 0.5227860745731715]
(39, 256, 176) (26, 256, 176)
(39, 256, 176) (35, 256, 176)
(39, 256, 176) (25, 256, 176)
(39, 256, 176) (29, 256, 176)
(39, 256, 176) (35, 256, 176)
(39, 256, 176) (31, 256, 176)
(39, 256, 176) (32, 256, 176)
(39, 256, 176) (34, 256, 176)
(39, 256, 176) (32, 256, 176)
(39, 256, 176) (32, 256, 176)
(39, 256, 176) (27, 256, 176)
(39, 256, 176) (27, 256, 176)
(39, 256, 176) (29, 256, 176)
(39, 256, 176) (38, 256, 176)
(39, 256, 176) (36, 256, 176)
(39, 256, 176) (27, 256, 176)
(39, 256, 176) (30, 256, 176)
(39, 256, 176) (32, 256, 176)
(39, 256, 176) (35, 256, 176)
(39, 256, 176) (39, 256, 176)
[0.16276461440831527, 0.5208642582742112]
(39, 256, 176) (38, 256, 176)
(39, 256, 176) (31, 256, 176)
(39, 256, 176) (30, 256, 176)
(39, 256, 176) (29, 256, 176)
(39, 256, 176) (39, 256, 176)
[0.3809064590117928, 0.6407421876055925]
(39, 256, 176) (28, 256, 176)
(39, 256, 176) (33, 256, 176)
(39, 256, 176) (26, 256, 176)
(39, 256, 176) (28, 256, 176)
(39, 

[0.344443204605792, 0.5538282127277745]
(34, 256, 176) (40, 256, 176)
(34, 256, 176) (32, 256, 176)
(34, 256, 176) (33, 256, 176)
(34, 256, 176) (34, 256, 176)
[0.027651827330132498, 0.41925112461976266]
(34, 256, 176) (23, 256, 176)
(34, 256, 176) (30, 256, 176)
(34, 256, 176) (26, 256, 176)
(34, 256, 176) (26, 256, 176)
(34, 256, 176) (32, 256, 176)
(34, 256, 176) (36, 256, 176)
(34, 256, 176) (29, 256, 176)
(34, 256, 176) (26, 256, 176)
(34, 256, 176) (35, 256, 176)
(34, 256, 176) (33, 256, 176)
(34, 256, 176) (39, 256, 176)
(34, 256, 176) (34, 256, 176)
[0.2745768870807029, 0.496916806781661]
(34, 256, 176) (31, 256, 176)
(34, 256, 176) (26, 256, 176)
(34, 256, 176) (32, 256, 176)
(34, 256, 176) (28, 256, 176)
(34, 256, 176) (29, 256, 176)
(34, 256, 176) (30, 256, 176)
(34, 256, 176) (38, 256, 176)
(34, 256, 176) (29, 256, 176)
(34, 256, 176) (26, 256, 176)
(34, 256, 176) (28, 256, 176)
(34, 256, 176) (33, 256, 176)
(34, 256, 176) (29, 256, 176)
(34, 256, 176) (34, 256, 176)
[0.283

[0.23309616601746078, 0.6010067278451514]
(36, 256, 176) (33, 256, 176)
(36, 256, 176) (33, 256, 176)
(36, 256, 176) (33, 256, 176)
(36, 256, 176) (34, 256, 176)
(36, 256, 176) (34, 256, 176)
(36, 256, 176) (32, 256, 176)
(36, 256, 176) (33, 256, 176)
(36, 256, 176) (30, 256, 176)
(36, 256, 176) (32, 256, 176)
(36, 256, 176) (24, 256, 176)
(36, 256, 176) (38, 256, 176)
(36, 256, 176) (32, 256, 176)
(36, 256, 176) (24, 256, 176)
(36, 256, 176) (38, 256, 176)
(36, 256, 176) (31, 256, 176)
(36, 256, 176) (32, 256, 176)
(36, 256, 176) (35, 256, 176)
(36, 256, 176) (27, 256, 176)
(36, 256, 176) (24, 256, 176)
(36, 256, 176) (32, 256, 176)
(36, 256, 176) (32, 256, 176)
(36, 256, 176) (25, 256, 176)
(36, 256, 176) (23, 256, 176)
(36, 256, 176) (27, 256, 176)
(36, 256, 176) (36, 256, 176)
[0.33214490479409514, 0.5940169989041132]
(36, 256, 176) (32, 256, 176)
(36, 256, 176) (34, 256, 176)
(36, 256, 176) (26, 256, 176)
(36, 256, 176) (30, 256, 176)
(36, 256, 176) (31, 256, 176)
(36, 256, 176) (

[0.09534480531332795, 0.44576295562559604]
(31, 256, 176) (32, 256, 176)
(31, 256, 176) (35, 256, 176)
(31, 256, 176) (27, 256, 176)
(31, 256, 176) (24, 256, 176)
(31, 256, 176) (32, 256, 176)
(31, 256, 176) (32, 256, 176)
(31, 256, 176) (25, 256, 176)
(31, 256, 176) (23, 256, 176)
(31, 256, 176) (27, 256, 176)
(31, 256, 176) (36, 256, 176)
(31, 256, 176) (32, 256, 176)
(31, 256, 176) (34, 256, 176)
(31, 256, 176) (26, 256, 176)
(31, 256, 176) (30, 256, 176)
(31, 256, 176) (31, 256, 176)
[0.3341123802381284, 0.4498946013656909]
(31, 256, 176) (32, 256, 176)
(31, 256, 176) (27, 256, 176)
(31, 256, 176) (31, 256, 176)
[0.04890184425339576, 0.4826578845251873]
(31, 256, 176) (33, 256, 176)
(31, 256, 176) (31, 256, 176)
[0.032146309893061914, 0.4814054505384946]
(31, 256, 176) (32, 256, 176)
(31, 256, 176) (35, 256, 176)
(31, 256, 176) (25, 256, 176)
(27, 256, 176) (29, 256, 176)
(27, 256, 176) (31, 256, 176)
(27, 256, 176) (32, 256, 176)
(27, 256, 176) (26, 256, 176)
(27, 256, 176) (33, 2

[0.12321428515011773, 0.5754674362564187]
(34, 256, 176) (32, 256, 176)
(34, 256, 176) (32, 256, 176)
(34, 256, 176) (27, 256, 176)
(34, 256, 176) (27, 256, 176)
(34, 256, 176) (29, 256, 176)
(34, 256, 176) (38, 256, 176)
(34, 256, 176) (36, 256, 176)
(34, 256, 176) (27, 256, 176)
(34, 256, 176) (30, 256, 176)
(34, 256, 176) (32, 256, 176)
(34, 256, 176) (35, 256, 176)
(34, 256, 176) (39, 256, 176)
(34, 256, 176) (38, 256, 176)
(34, 256, 176) (31, 256, 176)
(34, 256, 176) (30, 256, 176)
(34, 256, 176) (29, 256, 176)
(34, 256, 176) (39, 256, 176)
(34, 256, 176) (28, 256, 176)
(34, 256, 176) (33, 256, 176)
(34, 256, 176) (26, 256, 176)
(34, 256, 176) (28, 256, 176)
(34, 256, 176) (36, 256, 176)
(34, 256, 176) (33, 256, 176)
(34, 256, 176) (33, 256, 176)
(34, 256, 176) (33, 256, 176)
(34, 256, 176) (34, 256, 176)
[0.004740658088451433, 0.5715616316414769]
(34, 256, 176) (34, 256, 176)
[0.06783503870385735, 0.5300897759242794]
(34, 256, 176) (32, 256, 176)
(34, 256, 176) (33, 256, 176)
(34

[0.3124802370817099, 0.5537053510541388]
(36, 256, 176) (32, 256, 176)
(36, 256, 176) (34, 256, 176)
(36, 256, 176) (26, 256, 176)
(36, 256, 176) (30, 256, 176)
(36, 256, 176) (31, 256, 176)
(36, 256, 176) (32, 256, 176)
(36, 256, 176) (27, 256, 176)
(36, 256, 176) (31, 256, 176)
(36, 256, 176) (33, 256, 176)
(36, 256, 176) (31, 256, 176)
(36, 256, 176) (32, 256, 176)
(36, 256, 176) (35, 256, 176)
(36, 256, 176) (25, 256, 176)
(29, 256, 176) (29, 256, 176)
[0.3022049878435719, 0.5171983467057392]
(29, 256, 176) (31, 256, 176)
(29, 256, 176) (32, 256, 176)
(29, 256, 176) (26, 256, 176)
(29, 256, 176) (33, 256, 176)
(29, 256, 176) (33, 256, 176)
(29, 256, 176) (42, 256, 176)
(29, 256, 176) (28, 256, 176)
(29, 256, 176) (30, 256, 176)
(29, 256, 176) (26, 256, 176)
(29, 256, 176) (37, 256, 176)
(29, 256, 176) (24, 256, 176)
(29, 256, 176) (40, 256, 176)
(29, 256, 176) (28, 256, 176)
(29, 256, 176) (30, 256, 176)
(29, 256, 176) (39, 256, 176)
(29, 256, 176) (27, 256, 176)
(29, 256, 176) (34

[0.3155651959573673, 0.5621965225073168]
(32, 256, 176) (24, 256, 176)
(32, 256, 176) (25, 256, 176)
(32, 256, 176) (27, 256, 176)
(32, 256, 176) (39, 256, 176)
(32, 256, 176) (26, 256, 176)
(32, 256, 176) (35, 256, 176)
(32, 256, 176) (25, 256, 176)
(32, 256, 176) (29, 256, 176)
(32, 256, 176) (35, 256, 176)
(32, 256, 176) (31, 256, 176)
(32, 256, 176) (32, 256, 176)
[0.29115758835718536, 0.4245693628251082]
(32, 256, 176) (34, 256, 176)
(32, 256, 176) (32, 256, 176)
[0.20742357986176108, 0.4982653753768523]
(32, 256, 176) (32, 256, 176)
[0.36350608854308053, 0.6625497685439163]
(32, 256, 176) (27, 256, 176)
(32, 256, 176) (27, 256, 176)
(32, 256, 176) (29, 256, 176)
(32, 256, 176) (38, 256, 176)
(32, 256, 176) (36, 256, 176)
(32, 256, 176) (27, 256, 176)
(32, 256, 176) (30, 256, 176)
(32, 256, 176) (32, 256, 176)
[0.2369642358860486, 0.5752956843536949]
(32, 256, 176) (35, 256, 176)
(32, 256, 176) (39, 256, 176)
(32, 256, 176) (38, 256, 176)
(32, 256, 176) (31, 256, 176)
(32, 256, 17

[0.3893732382139546, 0.5682272586674975]
(28, 256, 176) (33, 256, 176)
(28, 256, 176) (29, 256, 176)
(28, 256, 176) (34, 256, 176)
(28, 256, 176) (32, 256, 176)
(28, 256, 176) (24, 256, 176)
(28, 256, 176) (25, 256, 176)
(28, 256, 176) (27, 256, 176)
(28, 256, 176) (39, 256, 176)
(28, 256, 176) (26, 256, 176)
(28, 256, 176) (35, 256, 176)
(28, 256, 176) (25, 256, 176)
(28, 256, 176) (29, 256, 176)
(28, 256, 176) (35, 256, 176)
(28, 256, 176) (31, 256, 176)
(28, 256, 176) (32, 256, 176)
(28, 256, 176) (34, 256, 176)
(28, 256, 176) (32, 256, 176)
(28, 256, 176) (32, 256, 176)
(28, 256, 176) (27, 256, 176)
(28, 256, 176) (27, 256, 176)
(28, 256, 176) (29, 256, 176)
(28, 256, 176) (38, 256, 176)
(28, 256, 176) (36, 256, 176)
(28, 256, 176) (27, 256, 176)
(28, 256, 176) (30, 256, 176)
(28, 256, 176) (32, 256, 176)
(28, 256, 176) (35, 256, 176)
(28, 256, 176) (39, 256, 176)
(28, 256, 176) (38, 256, 176)
(28, 256, 176) (31, 256, 176)
(28, 256, 176) (30, 256, 176)
(28, 256, 176) (29, 256, 176)

[0.0773952368589845, 0.5003066662094521]
(34, 256, 176) (23, 256, 176)
(34, 256, 176) (30, 256, 176)
(34, 256, 176) (26, 256, 176)
(34, 256, 176) (26, 256, 176)
(34, 256, 176) (32, 256, 176)
(34, 256, 176) (36, 256, 176)
(34, 256, 176) (29, 256, 176)
(34, 256, 176) (26, 256, 176)
(34, 256, 176) (35, 256, 176)
(34, 256, 176) (33, 256, 176)
(34, 256, 176) (39, 256, 176)
(34, 256, 176) (34, 256, 176)
[0.2716584699523537, 0.49493815482141507]
(34, 256, 176) (31, 256, 176)
(34, 256, 176) (26, 256, 176)
(34, 256, 176) (32, 256, 176)
(34, 256, 176) (28, 256, 176)
(34, 256, 176) (29, 256, 176)
(34, 256, 176) (30, 256, 176)
(34, 256, 176) (38, 256, 176)
(34, 256, 176) (29, 256, 176)
(34, 256, 176) (26, 256, 176)
(34, 256, 176) (28, 256, 176)
(34, 256, 176) (33, 256, 176)
(34, 256, 176) (29, 256, 176)
(34, 256, 176) (34, 256, 176)
[0.09226445607190409, 0.3405876788144239]
(34, 256, 176) (32, 256, 176)
(34, 256, 176) (24, 256, 176)
(34, 256, 176) (25, 256, 176)
(34, 256, 176) (27, 256, 176)
(34, 

(37, 256, 176) (40, 256, 176)
(37, 256, 176) (28, 256, 176)
(37, 256, 176) (30, 256, 176)
(37, 256, 176) (39, 256, 176)
(37, 256, 176) (27, 256, 176)
(37, 256, 176) (34, 256, 176)
(37, 256, 176) (28, 256, 176)
(37, 256, 176) (36, 256, 176)
(37, 256, 176) (32, 256, 176)
(37, 256, 176) (31, 256, 176)
(37, 256, 176) (27, 256, 176)
(37, 256, 176) (34, 256, 176)
(37, 256, 176) (29, 256, 176)
(37, 256, 176) (36, 256, 176)
(37, 256, 176) (29, 256, 176)
(37, 256, 176) (32, 256, 176)
(37, 256, 176) (31, 256, 176)
(37, 256, 176) (28, 256, 176)
(37, 256, 176) (28, 256, 176)
(37, 256, 176) (34, 256, 176)
(37, 256, 176) (24, 256, 176)
(37, 256, 176) (37, 256, 176)
(37, 256, 176) (30, 256, 176)
(37, 256, 176) (32, 256, 176)
(37, 256, 176) (23, 256, 176)
(37, 256, 176) (25, 256, 176)
(37, 256, 176) (29, 256, 176)
(37, 256, 176) (31, 256, 176)
(37, 256, 176) (41, 256, 176)
(37, 256, 176) (29, 256, 176)
(37, 256, 176) (25, 256, 176)
(37, 256, 176) (28, 256, 176)
(37, 256, 176) (38, 256, 176)
(37, 256, 

[0.1663087107450863, 0.5668272064448376]
(30, 256, 176) (32, 256, 176)
(30, 256, 176) (24, 256, 176)
(30, 256, 176) (38, 256, 176)
(30, 256, 176) (32, 256, 176)
(30, 256, 176) (24, 256, 176)
(30, 256, 176) (38, 256, 176)
(30, 256, 176) (31, 256, 176)
(30, 256, 176) (32, 256, 176)
(30, 256, 176) (35, 256, 176)
(30, 256, 176) (27, 256, 176)
(30, 256, 176) (24, 256, 176)
(30, 256, 176) (32, 256, 176)
(30, 256, 176) (32, 256, 176)
(30, 256, 176) (25, 256, 176)
(30, 256, 176) (23, 256, 176)
(30, 256, 176) (27, 256, 176)
(30, 256, 176) (36, 256, 176)
(30, 256, 176) (32, 256, 176)
(30, 256, 176) (34, 256, 176)
(30, 256, 176) (26, 256, 176)
(30, 256, 176) (30, 256, 176)
[0.15224265047287358, 0.5519943903954259]
(30, 256, 176) (31, 256, 176)
(30, 256, 176) (32, 256, 176)
(30, 256, 176) (27, 256, 176)
(30, 256, 176) (31, 256, 176)
(30, 256, 176) (33, 256, 176)
(30, 256, 176) (31, 256, 176)
(30, 256, 176) (32, 256, 176)
(30, 256, 176) (35, 256, 176)
(30, 256, 176) (25, 256, 176)
(32, 256, 176) (2

(25, 256, 176) (30, 256, 176)
(25, 256, 176) (39, 256, 176)
(25, 256, 176) (27, 256, 176)
(25, 256, 176) (34, 256, 176)
(25, 256, 176) (28, 256, 176)
(25, 256, 176) (36, 256, 176)
(25, 256, 176) (32, 256, 176)
(25, 256, 176) (31, 256, 176)
(25, 256, 176) (27, 256, 176)
(25, 256, 176) (34, 256, 176)
(25, 256, 176) (29, 256, 176)
(25, 256, 176) (36, 256, 176)
(25, 256, 176) (29, 256, 176)
(25, 256, 176) (32, 256, 176)
(25, 256, 176) (31, 256, 176)
(25, 256, 176) (28, 256, 176)
(25, 256, 176) (28, 256, 176)
(25, 256, 176) (34, 256, 176)
(25, 256, 176) (24, 256, 176)
(25, 256, 176) (37, 256, 176)
(25, 256, 176) (30, 256, 176)
(25, 256, 176) (32, 256, 176)
(25, 256, 176) (23, 256, 176)
(25, 256, 176) (25, 256, 176)
(25, 256, 176) (29, 256, 176)
(25, 256, 176) (31, 256, 176)
(25, 256, 176) (41, 256, 176)
(25, 256, 176) (29, 256, 176)
(25, 256, 176) (25, 256, 176)
[0.3296293937140641, 0.355020178154891]
(25, 256, 176) (28, 256, 176)
(25, 256, 176) (38, 256, 176)
(25, 256, 176) (30, 256, 176)


[0.37826341758387055, 0.5027202030869609]
(31, 256, 176) (33, 256, 176)
(31, 256, 176) (27, 256, 176)
(31, 256, 176) (26, 256, 176)
(31, 256, 176) (29, 256, 176)
(31, 256, 176) (37, 256, 176)
(31, 256, 176) (40, 256, 176)
(31, 256, 176) (34, 256, 176)
(31, 256, 176) (40, 256, 176)
(31, 256, 176) (32, 256, 176)
(31, 256, 176) (33, 256, 176)
(31, 256, 176) (34, 256, 176)
(31, 256, 176) (23, 256, 176)
(31, 256, 176) (30, 256, 176)
(31, 256, 176) (26, 256, 176)
(31, 256, 176) (26, 256, 176)
(31, 256, 176) (32, 256, 176)
(31, 256, 176) (36, 256, 176)
(31, 256, 176) (29, 256, 176)
(31, 256, 176) (26, 256, 176)
(31, 256, 176) (35, 256, 176)
(31, 256, 176) (33, 256, 176)
(31, 256, 176) (39, 256, 176)
(31, 256, 176) (34, 256, 176)
(31, 256, 176) (31, 256, 176)
[0.27187120126445197, 0.5560600210134227]
(31, 256, 176) (26, 256, 176)
(31, 256, 176) (32, 256, 176)
(31, 256, 176) (28, 256, 176)
(31, 256, 176) (29, 256, 176)
(31, 256, 176) (30, 256, 176)
(31, 256, 176) (38, 256, 176)
(31, 256, 176) (

[0.35496851604900576, 0.5079005236261027]
(29, 256, 176) (32, 256, 176)
(29, 256, 176) (31, 256, 176)
(29, 256, 176) (28, 256, 176)
(29, 256, 176) (28, 256, 176)
(29, 256, 176) (34, 256, 176)
(29, 256, 176) (24, 256, 176)
(29, 256, 176) (37, 256, 176)
(29, 256, 176) (30, 256, 176)
(29, 256, 176) (32, 256, 176)
(29, 256, 176) (23, 256, 176)
(29, 256, 176) (25, 256, 176)
(29, 256, 176) (29, 256, 176)
[0.2389729113506156, 0.5357771012728111]
(29, 256, 176) (31, 256, 176)
(29, 256, 176) (41, 256, 176)
(29, 256, 176) (29, 256, 176)
(29, 256, 176) (25, 256, 176)
(29, 256, 176) (28, 256, 176)
(29, 256, 176) (38, 256, 176)
(29, 256, 176) (30, 256, 176)
(29, 256, 176) (32, 256, 176)
(29, 256, 176) (31, 256, 176)
(29, 256, 176) (33, 256, 176)
(29, 256, 176) (27, 256, 176)
(29, 256, 176) (26, 256, 176)
(29, 256, 176) (29, 256, 176)
[0.3215844064695801, 0.282256569348419]
(29, 256, 176) (37, 256, 176)
(29, 256, 176) (40, 256, 176)
(29, 256, 176) (34, 256, 176)
(29, 256, 176) (40, 256, 176)
(29, 25

[0.2857899365355108, 0.6064590213728813]
(28, 256, 176) (30, 256, 176)
(28, 256, 176) (39, 256, 176)
(28, 256, 176) (27, 256, 176)
(28, 256, 176) (34, 256, 176)
(28, 256, 176) (28, 256, 176)
[0.07271713756604267, 0.5815268608286277]
(28, 256, 176) (36, 256, 176)
(28, 256, 176) (32, 256, 176)
(28, 256, 176) (31, 256, 176)
(28, 256, 176) (27, 256, 176)
(28, 256, 176) (34, 256, 176)
(28, 256, 176) (29, 256, 176)
(28, 256, 176) (36, 256, 176)
(28, 256, 176) (29, 256, 176)
(28, 256, 176) (32, 256, 176)
(28, 256, 176) (31, 256, 176)
(28, 256, 176) (28, 256, 176)
[0.06448937893417504, 0.5680616851177221]
(28, 256, 176) (28, 256, 176)
[0.17095673615322737, 0.6497529275144663]
(28, 256, 176) (34, 256, 176)
(28, 256, 176) (24, 256, 176)
(28, 256, 176) (37, 256, 176)
(28, 256, 176) (30, 256, 176)
(28, 256, 176) (32, 256, 176)
(28, 256, 176) (23, 256, 176)
(28, 256, 176) (25, 256, 176)
(28, 256, 176) (29, 256, 176)
(28, 256, 176) (31, 256, 176)
(28, 256, 176) (41, 256, 176)
(28, 256, 176) (29, 256

[0.2984739661955218, 0.5884047254783313]
(30, 256, 176) (26, 256, 176)
(30, 256, 176) (37, 256, 176)
(30, 256, 176) (24, 256, 176)
(30, 256, 176) (40, 256, 176)
(30, 256, 176) (28, 256, 176)
(30, 256, 176) (30, 256, 176)
[0.4619985019810709, 0.7165688961517328]
(30, 256, 176) (39, 256, 176)
(30, 256, 176) (27, 256, 176)
(30, 256, 176) (34, 256, 176)
(30, 256, 176) (28, 256, 176)
(30, 256, 176) (36, 256, 176)
(30, 256, 176) (32, 256, 176)
(30, 256, 176) (31, 256, 176)
(30, 256, 176) (27, 256, 176)
(30, 256, 176) (34, 256, 176)
(30, 256, 176) (29, 256, 176)
(30, 256, 176) (36, 256, 176)
(30, 256, 176) (29, 256, 176)
(30, 256, 176) (32, 256, 176)
(30, 256, 176) (31, 256, 176)
(30, 256, 176) (28, 256, 176)
(30, 256, 176) (28, 256, 176)
(30, 256, 176) (34, 256, 176)
(30, 256, 176) (24, 256, 176)
(30, 256, 176) (37, 256, 176)
(30, 256, 176) (30, 256, 176)
[0.028881971582987335, 0.47480579519082955]
(30, 256, 176) (32, 256, 176)
(30, 256, 176) (23, 256, 176)
(30, 256, 176) (25, 256, 176)
(30,

[0.1222820580544922, 0.5528360184416857]
(32, 256, 176) (35, 256, 176)
(32, 256, 176) (39, 256, 176)
(32, 256, 176) (38, 256, 176)
(32, 256, 176) (31, 256, 176)
(32, 256, 176) (30, 256, 176)
(32, 256, 176) (29, 256, 176)
(32, 256, 176) (39, 256, 176)
(32, 256, 176) (28, 256, 176)
(32, 256, 176) (33, 256, 176)
(32, 256, 176) (26, 256, 176)
(32, 256, 176) (28, 256, 176)
(32, 256, 176) (36, 256, 176)
(32, 256, 176) (33, 256, 176)
(32, 256, 176) (33, 256, 176)
(32, 256, 176) (33, 256, 176)
(32, 256, 176) (34, 256, 176)
(32, 256, 176) (34, 256, 176)
(32, 256, 176) (32, 256, 176)
[0.10214136771773087, 0.5060060287105063]
(32, 256, 176) (33, 256, 176)
(32, 256, 176) (30, 256, 176)
(32, 256, 176) (32, 256, 176)
[0.35323760750642824, 0.500120262172202]
(32, 256, 176) (24, 256, 176)
(32, 256, 176) (38, 256, 176)
(32, 256, 176) (32, 256, 176)
[0.35387480275161975, 0.49613918643407046]
(32, 256, 176) (24, 256, 176)
(32, 256, 176) (38, 256, 176)
(32, 256, 176) (31, 256, 176)
(32, 256, 176) (32, 256

[0.26535235250503675, 0.5900611376225764]
(33, 256, 176) (29, 256, 176)
(33, 256, 176) (34, 256, 176)
(33, 256, 176) (32, 256, 176)
(33, 256, 176) (24, 256, 176)
(33, 256, 176) (25, 256, 176)
(33, 256, 176) (27, 256, 176)
(33, 256, 176) (39, 256, 176)
(33, 256, 176) (26, 256, 176)
(33, 256, 176) (35, 256, 176)
(33, 256, 176) (25, 256, 176)
(33, 256, 176) (29, 256, 176)
(33, 256, 176) (35, 256, 176)
(33, 256, 176) (31, 256, 176)
(33, 256, 176) (32, 256, 176)
(33, 256, 176) (34, 256, 176)
(33, 256, 176) (32, 256, 176)
(33, 256, 176) (32, 256, 176)
(33, 256, 176) (27, 256, 176)
(33, 256, 176) (27, 256, 176)
(33, 256, 176) (29, 256, 176)
(33, 256, 176) (38, 256, 176)
(33, 256, 176) (36, 256, 176)
(33, 256, 176) (27, 256, 176)
(33, 256, 176) (30, 256, 176)
(33, 256, 176) (32, 256, 176)
(33, 256, 176) (35, 256, 176)
(33, 256, 176) (39, 256, 176)
(33, 256, 176) (38, 256, 176)
(33, 256, 176) (31, 256, 176)
(33, 256, 176) (30, 256, 176)
(33, 256, 176) (29, 256, 176)
(33, 256, 176) (39, 256, 176

[0.0, 0.5664702530541295]
(26, 256, 176) (35, 256, 176)
(26, 256, 176) (33, 256, 176)
(26, 256, 176) (39, 256, 176)
(26, 256, 176) (34, 256, 176)
(26, 256, 176) (31, 256, 176)
(26, 256, 176) (26, 256, 176)
[0.008880627748031519, 0.5599853419323496]
(26, 256, 176) (32, 256, 176)
(26, 256, 176) (28, 256, 176)
(26, 256, 176) (29, 256, 176)
(26, 256, 176) (30, 256, 176)
(26, 256, 176) (38, 256, 176)
(26, 256, 176) (29, 256, 176)
(26, 256, 176) (26, 256, 176)
[0.29974608713422307, 0.7433246295269023]
(26, 256, 176) (28, 256, 176)
(26, 256, 176) (33, 256, 176)
(26, 256, 176) (29, 256, 176)
(26, 256, 176) (34, 256, 176)
(26, 256, 176) (32, 256, 176)
(26, 256, 176) (24, 256, 176)
(26, 256, 176) (25, 256, 176)
(26, 256, 176) (27, 256, 176)
(26, 256, 176) (39, 256, 176)
(26, 256, 176) (26, 256, 176)
[0.0, 0.5025250780449865]
(26, 256, 176) (35, 256, 176)
(26, 256, 176) (25, 256, 176)
(26, 256, 176) (29, 256, 176)
(26, 256, 176) (35, 256, 176)
(26, 256, 176) (31, 256, 176)
(26, 256, 176) (32, 256

(37, 256, 176) (23, 256, 176)
(37, 256, 176) (25, 256, 176)
(37, 256, 176) (29, 256, 176)
(37, 256, 176) (31, 256, 176)
(37, 256, 176) (41, 256, 176)
(37, 256, 176) (29, 256, 176)
(37, 256, 176) (25, 256, 176)
(37, 256, 176) (28, 256, 176)
(37, 256, 176) (38, 256, 176)
(37, 256, 176) (30, 256, 176)
(37, 256, 176) (32, 256, 176)
(37, 256, 176) (31, 256, 176)
(37, 256, 176) (33, 256, 176)
(37, 256, 176) (27, 256, 176)
(37, 256, 176) (26, 256, 176)
(37, 256, 176) (29, 256, 176)
(37, 256, 176) (37, 256, 176)
(37, 256, 176) (40, 256, 176)
(37, 256, 176) (34, 256, 176)
(37, 256, 176) (40, 256, 176)
(37, 256, 176) (32, 256, 176)
(37, 256, 176) (33, 256, 176)
(37, 256, 176) (34, 256, 176)
(37, 256, 176) (23, 256, 176)
(37, 256, 176) (30, 256, 176)
(37, 256, 176) (26, 256, 176)
(37, 256, 176) (26, 256, 176)
(37, 256, 176) (32, 256, 176)
(37, 256, 176) (36, 256, 176)
(37, 256, 176) (29, 256, 176)
(37, 256, 176) (26, 256, 176)
(37, 256, 176) (35, 256, 176)
(37, 256, 176) (33, 256, 176)
(37, 256, 

[0.11819601990545954, 0.6591475292788428]
(34, 256, 176) (29, 256, 176)
(34, 256, 176) (36, 256, 176)
(34, 256, 176) (29, 256, 176)
(34, 256, 176) (32, 256, 176)
(34, 256, 176) (31, 256, 176)
(34, 256, 176) (28, 256, 176)
(34, 256, 176) (28, 256, 176)
(34, 256, 176) (34, 256, 176)
[0.346199307391347, 0.5765144718076722]
(34, 256, 176) (24, 256, 176)
(34, 256, 176) (37, 256, 176)
(34, 256, 176) (30, 256, 176)
(34, 256, 176) (32, 256, 176)
(34, 256, 176) (23, 256, 176)
(34, 256, 176) (25, 256, 176)
(34, 256, 176) (29, 256, 176)
(34, 256, 176) (31, 256, 176)
(34, 256, 176) (41, 256, 176)
(34, 256, 176) (29, 256, 176)
(34, 256, 176) (25, 256, 176)
(34, 256, 176) (28, 256, 176)
(34, 256, 176) (38, 256, 176)
(34, 256, 176) (30, 256, 176)
(34, 256, 176) (32, 256, 176)
(34, 256, 176) (31, 256, 176)
(34, 256, 176) (33, 256, 176)
(34, 256, 176) (27, 256, 176)
(34, 256, 176) (26, 256, 176)
(34, 256, 176) (29, 256, 176)
(34, 256, 176) (37, 256, 176)
(34, 256, 176) (40, 256, 176)
(34, 256, 176) (34

[0.14833742997691346, 0.5149075798600913]
(32, 256, 176) (31, 256, 176)
(32, 256, 176) (33, 256, 176)
(32, 256, 176) (27, 256, 176)
(32, 256, 176) (26, 256, 176)
(32, 256, 176) (29, 256, 176)
(32, 256, 176) (37, 256, 176)
(32, 256, 176) (40, 256, 176)
(32, 256, 176) (34, 256, 176)
(32, 256, 176) (40, 256, 176)
(32, 256, 176) (32, 256, 176)
(32, 256, 176) (33, 256, 176)
(32, 256, 176) (34, 256, 176)
(32, 256, 176) (23, 256, 176)
(32, 256, 176) (30, 256, 176)
(32, 256, 176) (26, 256, 176)
(32, 256, 176) (26, 256, 176)
(32, 256, 176) (32, 256, 176)
[0.3845536117876541, 0.658657267492769]
(32, 256, 176) (36, 256, 176)
(32, 256, 176) (29, 256, 176)
(32, 256, 176) (26, 256, 176)
(32, 256, 176) (35, 256, 176)
(32, 256, 176) (33, 256, 176)
(32, 256, 176) (39, 256, 176)
(32, 256, 176) (34, 256, 176)
(32, 256, 176) (31, 256, 176)
(32, 256, 176) (26, 256, 176)
(32, 256, 176) (32, 256, 176)
[0.4458158560183109, 0.6179861705301782]
(32, 256, 176) (28, 256, 176)
(32, 256, 176) (29, 256, 176)
(32, 25

[0.0773952368589845, 0.5003066662094521]
(34, 256, 176) (24, 256, 176)
(34, 256, 176) (37, 256, 176)
(34, 256, 176) (30, 256, 176)
(34, 256, 176) (32, 256, 176)
(34, 256, 176) (23, 256, 176)
(34, 256, 176) (25, 256, 176)
(34, 256, 176) (29, 256, 176)
(34, 256, 176) (31, 256, 176)
(34, 256, 176) (41, 256, 176)
(34, 256, 176) (29, 256, 176)
(34, 256, 176) (25, 256, 176)
(34, 256, 176) (28, 256, 176)
(34, 256, 176) (38, 256, 176)
(34, 256, 176) (30, 256, 176)
(34, 256, 176) (32, 256, 176)
(34, 256, 176) (31, 256, 176)
(34, 256, 176) (33, 256, 176)
(34, 256, 176) (27, 256, 176)
(34, 256, 176) (26, 256, 176)
(34, 256, 176) (29, 256, 176)
(34, 256, 176) (37, 256, 176)
(34, 256, 176) (40, 256, 176)
(34, 256, 176) (34, 256, 176)
[0.16132899400013276, 0.5195468849858502]
(34, 256, 176) (40, 256, 176)
(34, 256, 176) (32, 256, 176)
(34, 256, 176) (33, 256, 176)
(34, 256, 176) (34, 256, 176)
(34, 256, 176) (23, 256, 176)
(34, 256, 176) (30, 256, 176)
(34, 256, 176) (26, 256, 176)
(34, 256, 176) (2

[0.4622405572503091, 0.5783131408818558]
(30, 256, 176) (26, 256, 176)
(30, 256, 176) (37, 256, 176)
(30, 256, 176) (24, 256, 176)
(30, 256, 176) (40, 256, 176)
(30, 256, 176) (28, 256, 176)
(30, 256, 176) (30, 256, 176)
[0.18321304663742088, 0.45751566389625353]
(30, 256, 176) (39, 256, 176)
(30, 256, 176) (27, 256, 176)
(30, 256, 176) (34, 256, 176)
(30, 256, 176) (28, 256, 176)
(30, 256, 176) (36, 256, 176)
(30, 256, 176) (32, 256, 176)
(30, 256, 176) (31, 256, 176)
(30, 256, 176) (27, 256, 176)
(30, 256, 176) (34, 256, 176)
(30, 256, 176) (29, 256, 176)
(30, 256, 176) (36, 256, 176)
(30, 256, 176) (29, 256, 176)
(30, 256, 176) (32, 256, 176)
(30, 256, 176) (31, 256, 176)
(30, 256, 176) (28, 256, 176)
(30, 256, 176) (28, 256, 176)
(30, 256, 176) (34, 256, 176)
(30, 256, 176) (24, 256, 176)
(30, 256, 176) (37, 256, 176)
(30, 256, 176) (30, 256, 176)
[0.05824069563653519, 0.6397359690175164]
(30, 256, 176) (32, 256, 176)
(30, 256, 176) (23, 256, 176)
(30, 256, 176) (25, 256, 176)
(30,

[0.33928468053802113, 0.5830956592481554]
(26, 256, 176) (28, 256, 176)
(26, 256, 176) (36, 256, 176)
(26, 256, 176) (33, 256, 176)
(26, 256, 176) (33, 256, 176)
(26, 256, 176) (33, 256, 176)
(26, 256, 176) (34, 256, 176)
(26, 256, 176) (34, 256, 176)
(26, 256, 176) (32, 256, 176)
(26, 256, 176) (33, 256, 176)
(26, 256, 176) (30, 256, 176)
(26, 256, 176) (32, 256, 176)
(26, 256, 176) (24, 256, 176)
(26, 256, 176) (38, 256, 176)
(26, 256, 176) (32, 256, 176)
(26, 256, 176) (24, 256, 176)
(26, 256, 176) (38, 256, 176)
(26, 256, 176) (31, 256, 176)
(26, 256, 176) (32, 256, 176)
(26, 256, 176) (35, 256, 176)
(26, 256, 176) (27, 256, 176)
(26, 256, 176) (24, 256, 176)
(26, 256, 176) (32, 256, 176)
(26, 256, 176) (32, 256, 176)
(26, 256, 176) (25, 256, 176)
(26, 256, 176) (23, 256, 176)
(26, 256, 176) (27, 256, 176)
(26, 256, 176) (36, 256, 176)
(26, 256, 176) (32, 256, 176)
(26, 256, 176) (34, 256, 176)
(26, 256, 176) (26, 256, 176)
[0.39891678583046003, 0.5253146248323091]
(26, 256, 176) (

[0.3845536117876541, 0.658657267492769]
(32, 256, 176) (33, 256, 176)
(32, 256, 176) (34, 256, 176)
(32, 256, 176) (23, 256, 176)
(32, 256, 176) (30, 256, 176)
(32, 256, 176) (26, 256, 176)
(32, 256, 176) (26, 256, 176)
(32, 256, 176) (32, 256, 176)
(32, 256, 176) (36, 256, 176)
(32, 256, 176) (29, 256, 176)
(32, 256, 176) (26, 256, 176)
(32, 256, 176) (35, 256, 176)
(32, 256, 176) (33, 256, 176)
(32, 256, 176) (39, 256, 176)
(32, 256, 176) (34, 256, 176)
(32, 256, 176) (31, 256, 176)
(32, 256, 176) (26, 256, 176)
(32, 256, 176) (32, 256, 176)
[0.31980056828204856, 0.5029919398443153]
(32, 256, 176) (28, 256, 176)
(32, 256, 176) (29, 256, 176)
(32, 256, 176) (30, 256, 176)
(32, 256, 176) (38, 256, 176)
(32, 256, 176) (29, 256, 176)
(32, 256, 176) (26, 256, 176)
(32, 256, 176) (28, 256, 176)
(32, 256, 176) (33, 256, 176)
(32, 256, 176) (29, 256, 176)
(32, 256, 176) (34, 256, 176)
(32, 256, 176) (32, 256, 176)
[0.31499465491847656, 0.6469919666322065]
(32, 256, 176) (24, 256, 176)
(32, 2

(29, 256, 176) (34, 256, 176)
(29, 256, 176) (24, 256, 176)
(29, 256, 176) (37, 256, 176)
(29, 256, 176) (30, 256, 176)
(29, 256, 176) (32, 256, 176)
(29, 256, 176) (23, 256, 176)
(29, 256, 176) (25, 256, 176)
(29, 256, 176) (29, 256, 176)
[0.026711328465933794, 0.694480913926045]
(29, 256, 176) (31, 256, 176)
(29, 256, 176) (41, 256, 176)
(29, 256, 176) (29, 256, 176)
[0.1095494209988359, 0.6068389691348327]
(29, 256, 176) (25, 256, 176)
(29, 256, 176) (28, 256, 176)
(29, 256, 176) (38, 256, 176)
(29, 256, 176) (30, 256, 176)
(29, 256, 176) (32, 256, 176)
(29, 256, 176) (31, 256, 176)
(29, 256, 176) (33, 256, 176)
(29, 256, 176) (27, 256, 176)
(29, 256, 176) (26, 256, 176)
(29, 256, 176) (29, 256, 176)
[0.11920475744149958, 0.38554072497475245]
(29, 256, 176) (37, 256, 176)
(29, 256, 176) (40, 256, 176)
(29, 256, 176) (34, 256, 176)
(29, 256, 176) (40, 256, 176)
(29, 256, 176) (32, 256, 176)
(29, 256, 176) (33, 256, 176)
(29, 256, 176) (34, 256, 176)
(29, 256, 176) (23, 256, 176)
(29,

[0.08555178470796833, 0.5500806690159249]
(35, 256, 176) (25, 256, 176)
(35, 256, 176) (29, 256, 176)
(35, 256, 176) (35, 256, 176)
[0.3479896074289884, 0.7143577744803978]
(35, 256, 176) (31, 256, 176)
(35, 256, 176) (32, 256, 176)
(35, 256, 176) (34, 256, 176)
(35, 256, 176) (32, 256, 176)
(35, 256, 176) (32, 256, 176)
(35, 256, 176) (27, 256, 176)
(35, 256, 176) (27, 256, 176)
(35, 256, 176) (29, 256, 176)
(35, 256, 176) (38, 256, 176)
(35, 256, 176) (36, 256, 176)
(35, 256, 176) (27, 256, 176)
(35, 256, 176) (30, 256, 176)
(35, 256, 176) (32, 256, 176)
(35, 256, 176) (35, 256, 176)
[0.3665829805138394, 0.6264929661682122]
(35, 256, 176) (39, 256, 176)
(35, 256, 176) (38, 256, 176)
(35, 256, 176) (31, 256, 176)
(35, 256, 176) (30, 256, 176)
(35, 256, 176) (29, 256, 176)
(35, 256, 176) (39, 256, 176)
(35, 256, 176) (28, 256, 176)
(35, 256, 176) (33, 256, 176)
(35, 256, 176) (26, 256, 176)
(35, 256, 176) (28, 256, 176)
(35, 256, 176) (36, 256, 176)
(35, 256, 176) (33, 256, 176)
(35, 2

[0.169818424525904, 0.5306541297416868]
(39, 256, 176) (26, 256, 176)
(39, 256, 176) (35, 256, 176)
(39, 256, 176) (25, 256, 176)
(39, 256, 176) (29, 256, 176)
(39, 256, 176) (35, 256, 176)
(39, 256, 176) (31, 256, 176)
(39, 256, 176) (32, 256, 176)
(39, 256, 176) (34, 256, 176)
(39, 256, 176) (32, 256, 176)
(39, 256, 176) (32, 256, 176)
(39, 256, 176) (27, 256, 176)
(39, 256, 176) (27, 256, 176)
(39, 256, 176) (29, 256, 176)
(39, 256, 176) (38, 256, 176)
(39, 256, 176) (36, 256, 176)
(39, 256, 176) (27, 256, 176)
(39, 256, 176) (30, 256, 176)
(39, 256, 176) (32, 256, 176)
(39, 256, 176) (35, 256, 176)
(39, 256, 176) (39, 256, 176)
[0.1948764463673905, 0.623233674009307]
(39, 256, 176) (38, 256, 176)
(39, 256, 176) (31, 256, 176)
(39, 256, 176) (30, 256, 176)
(39, 256, 176) (29, 256, 176)
(39, 256, 176) (39, 256, 176)
[0.1495552823587054, 0.5022249884100436]
(39, 256, 176) (28, 256, 176)
(39, 256, 176) (33, 256, 176)
(39, 256, 176) (26, 256, 176)
(39, 256, 176) (28, 256, 176)
(39, 256,

[0.4517249900577067, 0.3439377711762019]
(31, 256, 176) (33, 256, 176)
(31, 256, 176) (27, 256, 176)
(31, 256, 176) (26, 256, 176)
(31, 256, 176) (29, 256, 176)
(31, 256, 176) (37, 256, 176)
(31, 256, 176) (40, 256, 176)
(31, 256, 176) (34, 256, 176)
(31, 256, 176) (40, 256, 176)
(31, 256, 176) (32, 256, 176)
(31, 256, 176) (33, 256, 176)
(31, 256, 176) (34, 256, 176)
(31, 256, 176) (23, 256, 176)
(31, 256, 176) (30, 256, 176)
(31, 256, 176) (26, 256, 176)
(31, 256, 176) (26, 256, 176)
(31, 256, 176) (32, 256, 176)
(31, 256, 176) (36, 256, 176)
(31, 256, 176) (29, 256, 176)
(31, 256, 176) (26, 256, 176)
(31, 256, 176) (35, 256, 176)
(31, 256, 176) (33, 256, 176)
(31, 256, 176) (39, 256, 176)
(31, 256, 176) (34, 256, 176)
(31, 256, 176) (31, 256, 176)
(31, 256, 176) (26, 256, 176)
(31, 256, 176) (32, 256, 176)
(31, 256, 176) (28, 256, 176)
(31, 256, 176) (29, 256, 176)
(31, 256, 176) (30, 256, 176)
(31, 256, 176) (38, 256, 176)
(31, 256, 176) (29, 256, 176)
(31, 256, 176) (26, 256, 176)

[0.2515503862040399, 0.4793091065981207]
(32, 256, 176) (23, 256, 176)
(32, 256, 176) (25, 256, 176)
(32, 256, 176) (29, 256, 176)
(32, 256, 176) (31, 256, 176)
(32, 256, 176) (41, 256, 176)
(32, 256, 176) (29, 256, 176)
(32, 256, 176) (25, 256, 176)
(32, 256, 176) (28, 256, 176)
(32, 256, 176) (38, 256, 176)
(32, 256, 176) (30, 256, 176)
(32, 256, 176) (32, 256, 176)
[0.238015444273585, 0.5654511785139786]
(32, 256, 176) (31, 256, 176)
(32, 256, 176) (33, 256, 176)
(32, 256, 176) (27, 256, 176)
(32, 256, 176) (26, 256, 176)
(32, 256, 176) (29, 256, 176)
(32, 256, 176) (37, 256, 176)
(32, 256, 176) (40, 256, 176)
(32, 256, 176) (34, 256, 176)
(32, 256, 176) (40, 256, 176)
(32, 256, 176) (32, 256, 176)
[0.4458158560183109, 0.6179861705301782]
(32, 256, 176) (33, 256, 176)
(32, 256, 176) (34, 256, 176)
(32, 256, 176) (23, 256, 176)
(32, 256, 176) (30, 256, 176)
(32, 256, 176) (26, 256, 176)
(32, 256, 176) (26, 256, 176)
(32, 256, 176) (32, 256, 176)
[0.31980056828204856, 0.50299193984431

[0.4762556304229264, 0.6883386757778859]
(29, 256, 176) (32, 256, 176)
(29, 256, 176) (31, 256, 176)
(29, 256, 176) (28, 256, 176)
(29, 256, 176) (28, 256, 176)
(29, 256, 176) (34, 256, 176)
(29, 256, 176) (24, 256, 176)
(29, 256, 176) (37, 256, 176)
(29, 256, 176) (30, 256, 176)
(29, 256, 176) (32, 256, 176)
(29, 256, 176) (23, 256, 176)
(29, 256, 176) (25, 256, 176)
(29, 256, 176) (29, 256, 176)
[0.2767369547447118, 0.6026082619855495]
(29, 256, 176) (31, 256, 176)
(29, 256, 176) (41, 256, 176)
(29, 256, 176) (29, 256, 176)
[0.3578110617108578, 0.5579588104312074]
(29, 256, 176) (25, 256, 176)
(29, 256, 176) (28, 256, 176)
(29, 256, 176) (38, 256, 176)
(29, 256, 176) (30, 256, 176)
(29, 256, 176) (32, 256, 176)
(29, 256, 176) (31, 256, 176)
(29, 256, 176) (33, 256, 176)
(29, 256, 176) (27, 256, 176)
(29, 256, 176) (26, 256, 176)
(29, 256, 176) (29, 256, 176)
[0.24772192645706992, 0.41607075962554213]
(29, 256, 176) (37, 256, 176)
(29, 256, 176) (40, 256, 176)
(29, 256, 176) (34, 256,

[0.0935963539177578, 0.5735815472530921]
(38, 256, 176) (30, 256, 176)
(38, 256, 176) (32, 256, 176)
(38, 256, 176) (31, 256, 176)
(38, 256, 176) (33, 256, 176)
(38, 256, 176) (27, 256, 176)
(38, 256, 176) (26, 256, 176)
(38, 256, 176) (29, 256, 176)
(38, 256, 176) (37, 256, 176)
(38, 256, 176) (40, 256, 176)
(38, 256, 176) (34, 256, 176)
(38, 256, 176) (40, 256, 176)
(38, 256, 176) (32, 256, 176)
(38, 256, 176) (33, 256, 176)
(38, 256, 176) (34, 256, 176)
(38, 256, 176) (23, 256, 176)
(38, 256, 176) (30, 256, 176)
(38, 256, 176) (26, 256, 176)
(38, 256, 176) (26, 256, 176)
(38, 256, 176) (32, 256, 176)
(38, 256, 176) (36, 256, 176)
(38, 256, 176) (29, 256, 176)
(38, 256, 176) (26, 256, 176)
(38, 256, 176) (35, 256, 176)
(38, 256, 176) (33, 256, 176)
(38, 256, 176) (39, 256, 176)
(38, 256, 176) (34, 256, 176)
(38, 256, 176) (31, 256, 176)
(38, 256, 176) (26, 256, 176)
(38, 256, 176) (32, 256, 176)
(38, 256, 176) (28, 256, 176)
(38, 256, 176) (29, 256, 176)
(38, 256, 176) (30, 256, 176)

[0.12893626161164234, 0.578243758498392]
(26, 256, 176) (37, 256, 176)
(26, 256, 176) (24, 256, 176)
(26, 256, 176) (40, 256, 176)
(26, 256, 176) (28, 256, 176)
(26, 256, 176) (30, 256, 176)
(26, 256, 176) (39, 256, 176)
(26, 256, 176) (27, 256, 176)
(26, 256, 176) (34, 256, 176)
(26, 256, 176) (28, 256, 176)
(26, 256, 176) (36, 256, 176)
(26, 256, 176) (32, 256, 176)
(26, 256, 176) (31, 256, 176)
(26, 256, 176) (27, 256, 176)
(26, 256, 176) (34, 256, 176)
(26, 256, 176) (29, 256, 176)
(26, 256, 176) (36, 256, 176)
(26, 256, 176) (29, 256, 176)
(26, 256, 176) (32, 256, 176)
(26, 256, 176) (31, 256, 176)
(26, 256, 176) (28, 256, 176)
(26, 256, 176) (28, 256, 176)
(26, 256, 176) (34, 256, 176)
(26, 256, 176) (24, 256, 176)
(26, 256, 176) (37, 256, 176)
(26, 256, 176) (30, 256, 176)
(26, 256, 176) (32, 256, 176)
(26, 256, 176) (23, 256, 176)
(26, 256, 176) (25, 256, 176)
(26, 256, 176) (29, 256, 176)
(26, 256, 176) (31, 256, 176)
(26, 256, 176) (41, 256, 176)
(26, 256, 176) (29, 256, 176)

[0.26535235250503675, 0.5900611376225764]
(33, 256, 176) (27, 256, 176)
(33, 256, 176) (26, 256, 176)
(33, 256, 176) (29, 256, 176)
(33, 256, 176) (37, 256, 176)
(33, 256, 176) (40, 256, 176)
(33, 256, 176) (34, 256, 176)
(33, 256, 176) (40, 256, 176)
(33, 256, 176) (32, 256, 176)
(33, 256, 176) (33, 256, 176)
[0.04323676735331754, 0.3141560041058089]
(33, 256, 176) (34, 256, 176)
(33, 256, 176) (23, 256, 176)
(33, 256, 176) (30, 256, 176)
(33, 256, 176) (26, 256, 176)
(33, 256, 176) (26, 256, 176)
(33, 256, 176) (32, 256, 176)
(33, 256, 176) (36, 256, 176)
(33, 256, 176) (29, 256, 176)
(33, 256, 176) (26, 256, 176)
(33, 256, 176) (35, 256, 176)
(33, 256, 176) (33, 256, 176)
[0.1142619305534854, 0.505353756673233]
(33, 256, 176) (39, 256, 176)
(33, 256, 176) (34, 256, 176)
(33, 256, 176) (31, 256, 176)
(33, 256, 176) (26, 256, 176)
(33, 256, 176) (32, 256, 176)
(33, 256, 176) (28, 256, 176)
(33, 256, 176) (29, 256, 176)
(33, 256, 176) (30, 256, 176)
(33, 256, 176) (38, 256, 176)
(33, 2

[0.3145331939833004, 0.5196117367173166]
(34, 256, 176) (40, 256, 176)
(34, 256, 176) (32, 256, 176)
(34, 256, 176) (33, 256, 176)
(34, 256, 176) (34, 256, 176)
[0.04083087241202081, 0.29876754668222133]
(34, 256, 176) (23, 256, 176)
(34, 256, 176) (30, 256, 176)
(34, 256, 176) (26, 256, 176)
(34, 256, 176) (26, 256, 176)
(34, 256, 176) (32, 256, 176)
(34, 256, 176) (36, 256, 176)
(34, 256, 176) (29, 256, 176)
(34, 256, 176) (26, 256, 176)
(34, 256, 176) (35, 256, 176)
(34, 256, 176) (33, 256, 176)
(34, 256, 176) (39, 256, 176)
(34, 256, 176) (34, 256, 176)
[0.27915477302511255, 0.4962351613814443]
(34, 256, 176) (31, 256, 176)
(34, 256, 176) (26, 256, 176)
(34, 256, 176) (32, 256, 176)
(34, 256, 176) (28, 256, 176)
(34, 256, 176) (29, 256, 176)
(34, 256, 176) (30, 256, 176)
(34, 256, 176) (38, 256, 176)
(34, 256, 176) (29, 256, 176)
(34, 256, 176) (26, 256, 176)
(34, 256, 176) (28, 256, 176)
(34, 256, 176) (33, 256, 176)
(34, 256, 176) (29, 256, 176)
(34, 256, 176) (34, 256, 176)
(34,

[0.21286524111266794, 0.5398196556105591]
(32, 256, 176) (34, 256, 176)
(32, 256, 176) (26, 256, 176)
(32, 256, 176) (30, 256, 176)
(32, 256, 176) (31, 256, 176)
(32, 256, 176) (32, 256, 176)
[0.2958800079096308, 0.46387208194427454]
(32, 256, 176) (27, 256, 176)
(32, 256, 176) (31, 256, 176)
(32, 256, 176) (33, 256, 176)
(32, 256, 176) (31, 256, 176)
(32, 256, 176) (32, 256, 176)
[0.3040851998724956, 0.5176200016454804]
(32, 256, 176) (35, 256, 176)
(32, 256, 176) (25, 256, 176)
(24, 256, 176) (29, 256, 176)
(24, 256, 176) (31, 256, 176)
(24, 256, 176) (32, 256, 176)
(24, 256, 176) (26, 256, 176)
(24, 256, 176) (33, 256, 176)
(24, 256, 176) (33, 256, 176)
(24, 256, 176) (42, 256, 176)
(24, 256, 176) (28, 256, 176)
(24, 256, 176) (30, 256, 176)
(24, 256, 176) (26, 256, 176)
(24, 256, 176) (37, 256, 176)
(24, 256, 176) (24, 256, 176)
[0.33619264707489854, 0.4996812407533755]
(24, 256, 176) (40, 256, 176)
(24, 256, 176) (28, 256, 176)
(24, 256, 176) (30, 256, 176)
(24, 256, 176) (39, 256

[0.16278906190490575, 0.5422252005045396]
(27, 256, 176) (34, 256, 176)
(27, 256, 176) (28, 256, 176)
(27, 256, 176) (36, 256, 176)
(27, 256, 176) (32, 256, 176)
(27, 256, 176) (31, 256, 176)
(27, 256, 176) (27, 256, 176)
[0.2836397473416814, 0.617519872830929]
(27, 256, 176) (34, 256, 176)
(27, 256, 176) (29, 256, 176)
(27, 256, 176) (36, 256, 176)
(27, 256, 176) (29, 256, 176)
(27, 256, 176) (32, 256, 176)
(27, 256, 176) (31, 256, 176)
(27, 256, 176) (28, 256, 176)
(27, 256, 176) (28, 256, 176)
(27, 256, 176) (34, 256, 176)
(27, 256, 176) (24, 256, 176)
(27, 256, 176) (37, 256, 176)
(27, 256, 176) (30, 256, 176)
(27, 256, 176) (32, 256, 176)
(27, 256, 176) (23, 256, 176)
(27, 256, 176) (25, 256, 176)
(27, 256, 176) (29, 256, 176)
(27, 256, 176) (31, 256, 176)
(27, 256, 176) (41, 256, 176)
(27, 256, 176) (29, 256, 176)
(27, 256, 176) (25, 256, 176)
(27, 256, 176) (28, 256, 176)
(27, 256, 176) (38, 256, 176)
(27, 256, 176) (30, 256, 176)
(27, 256, 176) (32, 256, 176)
(27, 256, 176) (31

[0.20584254339136845, 0.6816846890362155]
(26, 256, 176) (37, 256, 176)
(26, 256, 176) (24, 256, 176)
(26, 256, 176) (40, 256, 176)
(26, 256, 176) (28, 256, 176)
(26, 256, 176) (30, 256, 176)
(26, 256, 176) (39, 256, 176)
(26, 256, 176) (27, 256, 176)
(26, 256, 176) (34, 256, 176)
(26, 256, 176) (28, 256, 176)
(26, 256, 176) (36, 256, 176)
(26, 256, 176) (32, 256, 176)
(26, 256, 176) (31, 256, 176)
(26, 256, 176) (27, 256, 176)
(26, 256, 176) (34, 256, 176)
(26, 256, 176) (29, 256, 176)
(26, 256, 176) (36, 256, 176)
(26, 256, 176) (29, 256, 176)
(26, 256, 176) (32, 256, 176)
(26, 256, 176) (31, 256, 176)
(26, 256, 176) (28, 256, 176)
(26, 256, 176) (28, 256, 176)
(26, 256, 176) (34, 256, 176)
(26, 256, 176) (24, 256, 176)
(26, 256, 176) (37, 256, 176)
(26, 256, 176) (30, 256, 176)
(26, 256, 176) (32, 256, 176)
(26, 256, 176) (23, 256, 176)
(26, 256, 176) (25, 256, 176)
(26, 256, 176) (29, 256, 176)
(26, 256, 176) (31, 256, 176)
(26, 256, 176) (41, 256, 176)
(26, 256, 176) (29, 256, 176

[0.1633724734638431, 0.564056866112432]
(25, 256, 176) (27, 256, 176)
(25, 256, 176) (39, 256, 176)
(25, 256, 176) (26, 256, 176)
(25, 256, 176) (35, 256, 176)
(25, 256, 176) (25, 256, 176)
(25, 256, 176) (29, 256, 176)
(25, 256, 176) (35, 256, 176)
(25, 256, 176) (31, 256, 176)
(25, 256, 176) (32, 256, 176)
(25, 256, 176) (34, 256, 176)
(25, 256, 176) (32, 256, 176)
(25, 256, 176) (32, 256, 176)
(25, 256, 176) (27, 256, 176)
(25, 256, 176) (27, 256, 176)
(25, 256, 176) (29, 256, 176)
(25, 256, 176) (38, 256, 176)
(25, 256, 176) (36, 256, 176)
(25, 256, 176) (27, 256, 176)
(25, 256, 176) (30, 256, 176)
(25, 256, 176) (32, 256, 176)
(25, 256, 176) (35, 256, 176)
(25, 256, 176) (39, 256, 176)
(25, 256, 176) (38, 256, 176)
(25, 256, 176) (31, 256, 176)
(25, 256, 176) (30, 256, 176)
(25, 256, 176) (29, 256, 176)
(25, 256, 176) (39, 256, 176)
(25, 256, 176) (28, 256, 176)
(25, 256, 176) (33, 256, 176)
(25, 256, 176) (26, 256, 176)
(25, 256, 176) (28, 256, 176)
(25, 256, 176) (36, 256, 176)


[0.3479896074289884, 0.7143577744803978]
(35, 256, 176) (33, 256, 176)
(35, 256, 176) (39, 256, 176)
(35, 256, 176) (34, 256, 176)
(35, 256, 176) (31, 256, 176)
(35, 256, 176) (26, 256, 176)
(35, 256, 176) (32, 256, 176)
(35, 256, 176) (28, 256, 176)
(35, 256, 176) (29, 256, 176)
(35, 256, 176) (30, 256, 176)
(35, 256, 176) (38, 256, 176)
(35, 256, 176) (29, 256, 176)
(35, 256, 176) (26, 256, 176)
(35, 256, 176) (28, 256, 176)
(35, 256, 176) (33, 256, 176)
(35, 256, 176) (29, 256, 176)
(35, 256, 176) (34, 256, 176)
(35, 256, 176) (32, 256, 176)
(35, 256, 176) (24, 256, 176)
(35, 256, 176) (25, 256, 176)
(35, 256, 176) (27, 256, 176)
(35, 256, 176) (39, 256, 176)
(35, 256, 176) (26, 256, 176)
(35, 256, 176) (35, 256, 176)
[0.17626268675609388, 0.5712386877789295]
(35, 256, 176) (25, 256, 176)
(35, 256, 176) (29, 256, 176)
(35, 256, 176) (35, 256, 176)
(35, 256, 176) (31, 256, 176)
(35, 256, 176) (32, 256, 176)
(35, 256, 176) (34, 256, 176)
(35, 256, 176) (32, 256, 176)
(35, 256, 176) (3

[0.1363788853926477, 0.531464090723303]
(32, 256, 176) (23, 256, 176)
(32, 256, 176) (25, 256, 176)
(32, 256, 176) (29, 256, 176)
(32, 256, 176) (31, 256, 176)
(32, 256, 176) (41, 256, 176)
(32, 256, 176) (29, 256, 176)
(32, 256, 176) (25, 256, 176)
(32, 256, 176) (28, 256, 176)
(32, 256, 176) (38, 256, 176)
(32, 256, 176) (30, 256, 176)
(32, 256, 176) (32, 256, 176)
[0.18722384412782203, 0.40205989047974205]
(32, 256, 176) (31, 256, 176)
(32, 256, 176) (33, 256, 176)
(32, 256, 176) (27, 256, 176)
(32, 256, 176) (26, 256, 176)
(32, 256, 176) (29, 256, 176)
(32, 256, 176) (37, 256, 176)
(32, 256, 176) (40, 256, 176)
(32, 256, 176) (34, 256, 176)
(32, 256, 176) (40, 256, 176)
(32, 256, 176) (32, 256, 176)
[0.2956907079168295, 0.49872299264572606]
(32, 256, 176) (33, 256, 176)
(32, 256, 176) (34, 256, 176)
(32, 256, 176) (23, 256, 176)
(32, 256, 176) (30, 256, 176)
(32, 256, 176) (26, 256, 176)
(32, 256, 176) (26, 256, 176)
(32, 256, 176) (32, 256, 176)
[0.2568965504586377, 0.628280376244

[0.2750053221054496, 0.43773716801734713]
(32, 256, 176) (31, 256, 176)
(32, 256, 176) (27, 256, 176)
(32, 256, 176) (34, 256, 176)
(32, 256, 176) (29, 256, 176)
(32, 256, 176) (36, 256, 176)
(32, 256, 176) (29, 256, 176)
(32, 256, 176) (32, 256, 176)
[0.20742357986176108, 0.4982653753768523]
(32, 256, 176) (31, 256, 176)
(32, 256, 176) (28, 256, 176)
(32, 256, 176) (28, 256, 176)
(32, 256, 176) (34, 256, 176)
(32, 256, 176) (24, 256, 176)
(32, 256, 176) (37, 256, 176)
(32, 256, 176) (30, 256, 176)
(32, 256, 176) (32, 256, 176)
[0.22789115474005175, 0.5297126214037957]
(32, 256, 176) (23, 256, 176)
(32, 256, 176) (25, 256, 176)
(32, 256, 176) (29, 256, 176)
(32, 256, 176) (31, 256, 176)
(32, 256, 176) (41, 256, 176)
(32, 256, 176) (29, 256, 176)
(32, 256, 176) (25, 256, 176)
(32, 256, 176) (28, 256, 176)
(32, 256, 176) (38, 256, 176)
(32, 256, 176) (30, 256, 176)
(32, 256, 176) (32, 256, 176)
[0.026948667334688817, 0.47315394400856925]
(32, 256, 176) (31, 256, 176)
(32, 256, 176) (33, 

[0.125198249987032, 0.6056348330238364]
(32, 256, 176) (32, 256, 176)
(32, 256, 176) (27, 256, 176)
(32, 256, 176) (27, 256, 176)
(32, 256, 176) (29, 256, 176)
(32, 256, 176) (38, 256, 176)
(32, 256, 176) (36, 256, 176)
(32, 256, 176) (27, 256, 176)
(32, 256, 176) (30, 256, 176)
(32, 256, 176) (32, 256, 176)
[0.2913346871183324, 0.6408757960345208]
(32, 256, 176) (35, 256, 176)
(32, 256, 176) (39, 256, 176)
(32, 256, 176) (38, 256, 176)
(32, 256, 176) (31, 256, 176)
(32, 256, 176) (30, 256, 176)
(32, 256, 176) (29, 256, 176)
(32, 256, 176) (39, 256, 176)
(32, 256, 176) (28, 256, 176)
(32, 256, 176) (33, 256, 176)
(32, 256, 176) (26, 256, 176)
(32, 256, 176) (28, 256, 176)
(32, 256, 176) (36, 256, 176)
(32, 256, 176) (33, 256, 176)
(32, 256, 176) (33, 256, 176)
(32, 256, 176) (33, 256, 176)
(32, 256, 176) (34, 256, 176)
(32, 256, 176) (34, 256, 176)
(32, 256, 176) (32, 256, 176)
[0.20093310509467813, 0.5567284732647925]
(32, 256, 176) (33, 256, 176)
(32, 256, 176) (30, 256, 176)
(32, 25

[0.2790764979440074, 0.22224076481543287]
(27, 256, 176) (30, 256, 176)
(27, 256, 176) (32, 256, 176)
(27, 256, 176) (35, 256, 176)
(27, 256, 176) (39, 256, 176)
(27, 256, 176) (38, 256, 176)
(27, 256, 176) (31, 256, 176)
(27, 256, 176) (30, 256, 176)
(27, 256, 176) (29, 256, 176)
(27, 256, 176) (39, 256, 176)
(27, 256, 176) (28, 256, 176)
(27, 256, 176) (33, 256, 176)
(27, 256, 176) (26, 256, 176)
(27, 256, 176) (28, 256, 176)
(27, 256, 176) (36, 256, 176)
(27, 256, 176) (33, 256, 176)
(27, 256, 176) (33, 256, 176)
(27, 256, 176) (33, 256, 176)
(27, 256, 176) (34, 256, 176)
(27, 256, 176) (34, 256, 176)
(27, 256, 176) (32, 256, 176)
(27, 256, 176) (33, 256, 176)
(27, 256, 176) (30, 256, 176)
(27, 256, 176) (32, 256, 176)
(27, 256, 176) (24, 256, 176)
(27, 256, 176) (38, 256, 176)
(27, 256, 176) (32, 256, 176)
(27, 256, 176) (24, 256, 176)
(27, 256, 176) (38, 256, 176)
(27, 256, 176) (31, 256, 176)
(27, 256, 176) (32, 256, 176)
(27, 256, 176) (35, 256, 176)
(27, 256, 176) (27, 256, 176

[0.18825670575193199, 0.682963379404817]
(38, 256, 176) (32, 256, 176)
(38, 256, 176) (24, 256, 176)
(38, 256, 176) (38, 256, 176)
[0.09603033314234181, 0.49978147739055534]
(38, 256, 176) (31, 256, 176)
(38, 256, 176) (32, 256, 176)
(38, 256, 176) (35, 256, 176)
(38, 256, 176) (27, 256, 176)
(38, 256, 176) (24, 256, 176)
(38, 256, 176) (32, 256, 176)
(38, 256, 176) (32, 256, 176)
(38, 256, 176) (25, 256, 176)
(38, 256, 176) (23, 256, 176)
(38, 256, 176) (27, 256, 176)
(38, 256, 176) (36, 256, 176)
(38, 256, 176) (32, 256, 176)
(38, 256, 176) (34, 256, 176)
(38, 256, 176) (26, 256, 176)
(38, 256, 176) (30, 256, 176)
(38, 256, 176) (31, 256, 176)
(38, 256, 176) (32, 256, 176)
(38, 256, 176) (27, 256, 176)
(38, 256, 176) (31, 256, 176)
(38, 256, 176) (33, 256, 176)
(38, 256, 176) (31, 256, 176)
(38, 256, 176) (32, 256, 176)
(38, 256, 176) (35, 256, 176)
(38, 256, 176) (25, 256, 176)
(36, 256, 176) (29, 256, 176)
(36, 256, 176) (31, 256, 176)
(36, 256, 176) (32, 256, 176)
(36, 256, 176) (

[0.28864746049389556, 0.40993201962303494]
(27, 256, 176) (36, 256, 176)
(27, 256, 176) (32, 256, 176)
(27, 256, 176) (34, 256, 176)
(27, 256, 176) (26, 256, 176)
(27, 256, 176) (30, 256, 176)
(27, 256, 176) (31, 256, 176)
(27, 256, 176) (32, 256, 176)
(27, 256, 176) (27, 256, 176)
[0.21151821213394176, 0.5462815662329966]
(27, 256, 176) (31, 256, 176)
(27, 256, 176) (33, 256, 176)
(27, 256, 176) (31, 256, 176)
(27, 256, 176) (32, 256, 176)
(27, 256, 176) (35, 256, 176)
(27, 256, 176) (25, 256, 176)
(30, 256, 176) (29, 256, 176)
(30, 256, 176) (31, 256, 176)
(30, 256, 176) (32, 256, 176)
(30, 256, 176) (26, 256, 176)
(30, 256, 176) (33, 256, 176)
(30, 256, 176) (33, 256, 176)
(30, 256, 176) (42, 256, 176)
(30, 256, 176) (28, 256, 176)
(30, 256, 176) (30, 256, 176)
[0.12552013846596316, 0.5972499969184352]
(30, 256, 176) (26, 256, 176)
(30, 256, 176) (37, 256, 176)
(30, 256, 176) (24, 256, 176)
(30, 256, 176) (40, 256, 176)
(30, 256, 176) (28, 256, 176)
(30, 256, 176) (30, 256, 176)
[0.

[0.05744858884834655, 0.39710219323813206]
(32, 256, 176) (33, 256, 176)
(32, 256, 176) (30, 256, 176)
(32, 256, 176) (32, 256, 176)
[0.2642282525215087, 0.5910290035864336]
(32, 256, 176) (24, 256, 176)
(32, 256, 176) (38, 256, 176)
(32, 256, 176) (32, 256, 176)
[0.20080923713034535, 0.566181037490696]
(32, 256, 176) (24, 256, 176)
(32, 256, 176) (38, 256, 176)
(32, 256, 176) (31, 256, 176)
(32, 256, 176) (32, 256, 176)
[0.1818317636245243, 0.5172506570289371]
(32, 256, 176) (35, 256, 176)
(32, 256, 176) (27, 256, 176)
(32, 256, 176) (24, 256, 176)
(32, 256, 176) (32, 256, 176)
[0.3665974105850988, 0.6107639671419162]
(32, 256, 176) (32, 256, 176)
[0.26822145159071525, 0.7167797492886641]
(32, 256, 176) (25, 256, 176)
(32, 256, 176) (23, 256, 176)
(32, 256, 176) (27, 256, 176)
(32, 256, 176) (36, 256, 176)
(32, 256, 176) (32, 256, 176)
[0.1596383873014807, 0.6181915482352739]
(32, 256, 176) (34, 256, 176)
(32, 256, 176) (26, 256, 176)
(32, 256, 176) (30, 256, 176)
(32, 256, 176) (31, 

[0.06625162092735865, 0.43647425364871856]
(39, 256, 176) (28, 256, 176)
(39, 256, 176) (33, 256, 176)
(39, 256, 176) (26, 256, 176)
(39, 256, 176) (28, 256, 176)
(39, 256, 176) (36, 256, 176)
(39, 256, 176) (33, 256, 176)
(39, 256, 176) (33, 256, 176)
(39, 256, 176) (33, 256, 176)
(39, 256, 176) (34, 256, 176)
(39, 256, 176) (34, 256, 176)
(39, 256, 176) (32, 256, 176)
(39, 256, 176) (33, 256, 176)
(39, 256, 176) (30, 256, 176)
(39, 256, 176) (32, 256, 176)
(39, 256, 176) (24, 256, 176)
(39, 256, 176) (38, 256, 176)
(39, 256, 176) (32, 256, 176)
(39, 256, 176) (24, 256, 176)
(39, 256, 176) (38, 256, 176)
(39, 256, 176) (31, 256, 176)
(39, 256, 176) (32, 256, 176)
(39, 256, 176) (35, 256, 176)
(39, 256, 176) (27, 256, 176)
(39, 256, 176) (24, 256, 176)
(39, 256, 176) (32, 256, 176)
(39, 256, 176) (32, 256, 176)
(39, 256, 176) (25, 256, 176)
(39, 256, 176) (23, 256, 176)
(39, 256, 176) (27, 256, 176)
(39, 256, 176) (36, 256, 176)
(39, 256, 176) (32, 256, 176)
(39, 256, 176) (34, 256, 17

[0.14159403754960195, 0.614189433743398]
(31, 256, 176) (32, 256, 176)
(31, 256, 176) (27, 256, 176)
(31, 256, 176) (31, 256, 176)
[0.4407818535668334, 0.5560406661785944]
(31, 256, 176) (33, 256, 176)
(31, 256, 176) (31, 256, 176)
[0.2282273729283299, 0.5272817067316188]
(31, 256, 176) (32, 256, 176)
(31, 256, 176) (35, 256, 176)
(31, 256, 176) (25, 256, 176)
(30, 256, 176) (29, 256, 176)
(30, 256, 176) (31, 256, 176)
(30, 256, 176) (32, 256, 176)
(30, 256, 176) (26, 256, 176)
(30, 256, 176) (33, 256, 176)
(30, 256, 176) (33, 256, 176)
(30, 256, 176) (42, 256, 176)
(30, 256, 176) (28, 256, 176)
(30, 256, 176) (30, 256, 176)
[0.22039864578769933, 0.6619159015556282]
(30, 256, 176) (26, 256, 176)
(30, 256, 176) (37, 256, 176)
(30, 256, 176) (24, 256, 176)
(30, 256, 176) (40, 256, 176)
(30, 256, 176) (28, 256, 176)
(30, 256, 176) (30, 256, 176)
[0.40291911145595677, 0.6133166032112292]
(30, 256, 176) (39, 256, 176)
(30, 256, 176) (27, 256, 176)
(30, 256, 176) (34, 256, 176)
(30, 256, 176

(39, 256, 176) (26, 256, 176)
(39, 256, 176) (32, 256, 176)
(39, 256, 176) (36, 256, 176)
(39, 256, 176) (29, 256, 176)
(39, 256, 176) (26, 256, 176)
(39, 256, 176) (35, 256, 176)
(39, 256, 176) (33, 256, 176)
(39, 256, 176) (39, 256, 176)
[0.1495552823587054, 0.5022249884100436]
(39, 256, 176) (34, 256, 176)
(39, 256, 176) (31, 256, 176)
(39, 256, 176) (26, 256, 176)
(39, 256, 176) (32, 256, 176)
(39, 256, 176) (28, 256, 176)
(39, 256, 176) (29, 256, 176)
(39, 256, 176) (30, 256, 176)
(39, 256, 176) (38, 256, 176)
(39, 256, 176) (29, 256, 176)
(39, 256, 176) (26, 256, 176)
(39, 256, 176) (28, 256, 176)
(39, 256, 176) (33, 256, 176)
(39, 256, 176) (29, 256, 176)
(39, 256, 176) (34, 256, 176)
(39, 256, 176) (32, 256, 176)
(39, 256, 176) (24, 256, 176)
(39, 256, 176) (25, 256, 176)
(39, 256, 176) (27, 256, 176)
(39, 256, 176) (39, 256, 176)
[0.06273250745180396, 0.4204542427815707]
(39, 256, 176) (26, 256, 176)
(39, 256, 176) (35, 256, 176)
(39, 256, 176) (25, 256, 176)
(39, 256, 176) (2

(33, 256, 176) (27, 256, 176)
(33, 256, 176) (26, 256, 176)
(33, 256, 176) (29, 256, 176)
(33, 256, 176) (37, 256, 176)
(33, 256, 176) (40, 256, 176)
(33, 256, 176) (34, 256, 176)
(33, 256, 176) (40, 256, 176)
(33, 256, 176) (32, 256, 176)
(33, 256, 176) (33, 256, 176)
[0.1812384034019109, 0.42259395053677645]
(33, 256, 176) (34, 256, 176)
(33, 256, 176) (23, 256, 176)
(33, 256, 176) (30, 256, 176)
(33, 256, 176) (26, 256, 176)
(33, 256, 176) (26, 256, 176)
(33, 256, 176) (32, 256, 176)
(33, 256, 176) (36, 256, 176)
(33, 256, 176) (29, 256, 176)
(33, 256, 176) (26, 256, 176)
(33, 256, 176) (35, 256, 176)
(33, 256, 176) (33, 256, 176)
[0.2508076343564897, 0.7161675188846486]
(33, 256, 176) (39, 256, 176)
(33, 256, 176) (34, 256, 176)
(33, 256, 176) (31, 256, 176)
(33, 256, 176) (26, 256, 176)
(33, 256, 176) (32, 256, 176)
(33, 256, 176) (28, 256, 176)
(33, 256, 176) (29, 256, 176)
(33, 256, 176) (30, 256, 176)
(33, 256, 176) (38, 256, 176)
(33, 256, 176) (29, 256, 176)
(33, 256, 176) (2

[0.1348746647122187, 0.6942039642734352]
(28, 256, 176) (30, 256, 176)
(28, 256, 176) (26, 256, 176)
(28, 256, 176) (37, 256, 176)
(28, 256, 176) (24, 256, 176)
(28, 256, 176) (40, 256, 176)
(28, 256, 176) (28, 256, 176)
[0.20292193544299197, 0.5640133898419069]
(28, 256, 176) (30, 256, 176)
(28, 256, 176) (39, 256, 176)
(28, 256, 176) (27, 256, 176)
(28, 256, 176) (34, 256, 176)
(28, 256, 176) (28, 256, 176)
[0.2563048745735808, 0.6595364344253009]
(28, 256, 176) (36, 256, 176)
(28, 256, 176) (32, 256, 176)
(28, 256, 176) (31, 256, 176)
(28, 256, 176) (27, 256, 176)
(28, 256, 176) (34, 256, 176)
(28, 256, 176) (29, 256, 176)
(28, 256, 176) (36, 256, 176)
(28, 256, 176) (29, 256, 176)
(28, 256, 176) (32, 256, 176)
(28, 256, 176) (31, 256, 176)
(28, 256, 176) (28, 256, 176)
[0.18019582975260143, 0.6837181925614644]
(28, 256, 176) (28, 256, 176)
[0.25528709854017534, 0.6473333124337419]
(28, 256, 176) (34, 256, 176)
(28, 256, 176) (24, 256, 176)
(28, 256, 176) (37, 256, 176)
(28, 256, 17

[0.3614670775012502, 0.6415505796115396]
(36, 256, 176) (32, 256, 176)
(36, 256, 176) (34, 256, 176)
(36, 256, 176) (26, 256, 176)
(36, 256, 176) (30, 256, 176)
(36, 256, 176) (31, 256, 176)
(36, 256, 176) (32, 256, 176)
(36, 256, 176) (27, 256, 176)
(36, 256, 176) (31, 256, 176)
(36, 256, 176) (33, 256, 176)
(36, 256, 176) (31, 256, 176)
(36, 256, 176) (32, 256, 176)
(36, 256, 176) (35, 256, 176)
(36, 256, 176) (25, 256, 176)
(33, 256, 176) (29, 256, 176)
(33, 256, 176) (31, 256, 176)
(33, 256, 176) (32, 256, 176)
(33, 256, 176) (26, 256, 176)
(33, 256, 176) (33, 256, 176)
[0.4276384115508505, 0.5983411611883969]
(33, 256, 176) (33, 256, 176)
[0.16217783080072823, 0.5631107547053733]
(33, 256, 176) (42, 256, 176)
(33, 256, 176) (28, 256, 176)
(33, 256, 176) (30, 256, 176)
(33, 256, 176) (26, 256, 176)
(33, 256, 176) (37, 256, 176)
(33, 256, 176) (24, 256, 176)
(33, 256, 176) (40, 256, 176)
(33, 256, 176) (28, 256, 176)
(33, 256, 176) (30, 256, 176)
(33, 256, 176) (39, 256, 176)
(33, 2

[0.1716117665852919, 0.5259567628574993]
(33, 256, 176) (26, 256, 176)
(33, 256, 176) (28, 256, 176)
(33, 256, 176) (36, 256, 176)
(33, 256, 176) (33, 256, 176)
[0.15725669034082485, 0.4537677268520651]
(33, 256, 176) (33, 256, 176)
(33, 256, 176) (33, 256, 176)
[0.06758750122309574, 0.6530085538127606]
(33, 256, 176) (34, 256, 176)
(33, 256, 176) (34, 256, 176)
(33, 256, 176) (32, 256, 176)
(33, 256, 176) (33, 256, 176)
[0.04785741763651786, 0.4427493709793243]
(33, 256, 176) (30, 256, 176)
(33, 256, 176) (32, 256, 176)
(33, 256, 176) (24, 256, 176)
(33, 256, 176) (38, 256, 176)
(33, 256, 176) (32, 256, 176)
(33, 256, 176) (24, 256, 176)
(33, 256, 176) (38, 256, 176)
(33, 256, 176) (31, 256, 176)
(33, 256, 176) (32, 256, 176)
(33, 256, 176) (35, 256, 176)
(33, 256, 176) (27, 256, 176)
(33, 256, 176) (24, 256, 176)
(33, 256, 176) (32, 256, 176)
(33, 256, 176) (32, 256, 176)
(33, 256, 176) (25, 256, 176)
(33, 256, 176) (23, 256, 176)
(33, 256, 176) (27, 256, 176)
(33, 256, 176) (36, 256

[0.00871520939715935, 0.3847287118777875]
(34, 256, 176) (23, 256, 176)
(34, 256, 176) (30, 256, 176)
(34, 256, 176) (26, 256, 176)
(34, 256, 176) (26, 256, 176)
(34, 256, 176) (32, 256, 176)
(34, 256, 176) (36, 256, 176)
(34, 256, 176) (29, 256, 176)
(34, 256, 176) (26, 256, 176)
(34, 256, 176) (35, 256, 176)
(34, 256, 176) (33, 256, 176)
(34, 256, 176) (39, 256, 176)
(34, 256, 176) (34, 256, 176)
[0.11497145013562639, 0.46518435172875344]
(34, 256, 176) (31, 256, 176)
(34, 256, 176) (26, 256, 176)
(34, 256, 176) (32, 256, 176)
(34, 256, 176) (28, 256, 176)
(34, 256, 176) (29, 256, 176)
(34, 256, 176) (30, 256, 176)
(34, 256, 176) (38, 256, 176)
(34, 256, 176) (29, 256, 176)
(34, 256, 176) (26, 256, 176)
(34, 256, 176) (28, 256, 176)
(34, 256, 176) (33, 256, 176)
(34, 256, 176) (29, 256, 176)
(34, 256, 176) (34, 256, 176)
[0.1039304604186794, 0.3815781966174455]
(34, 256, 176) (32, 256, 176)
(34, 256, 176) (24, 256, 176)
(34, 256, 176) (25, 256, 176)
(34, 256, 176) (27, 256, 176)
(34,

[0.2850036725736042, 0.6206206734459415]
(32, 256, 176) (31, 256, 176)
(32, 256, 176) (28, 256, 176)
(32, 256, 176) (28, 256, 176)
(32, 256, 176) (34, 256, 176)
(32, 256, 176) (24, 256, 176)
(32, 256, 176) (37, 256, 176)
(32, 256, 176) (30, 256, 176)
(32, 256, 176) (32, 256, 176)
[0.2001010080797878, 0.5303293172296514]
(32, 256, 176) (23, 256, 176)
(32, 256, 176) (25, 256, 176)
(32, 256, 176) (29, 256, 176)
(32, 256, 176) (31, 256, 176)
(32, 256, 176) (41, 256, 176)
(32, 256, 176) (29, 256, 176)
(32, 256, 176) (25, 256, 176)
(32, 256, 176) (28, 256, 176)
(32, 256, 176) (38, 256, 176)
(32, 256, 176) (30, 256, 176)
(32, 256, 176) (32, 256, 176)
[0.10214136771773087, 0.5060060287105063]
(32, 256, 176) (31, 256, 176)
(32, 256, 176) (33, 256, 176)
(32, 256, 176) (27, 256, 176)
(32, 256, 176) (26, 256, 176)
(32, 256, 176) (29, 256, 176)
(32, 256, 176) (37, 256, 176)
(32, 256, 176) (40, 256, 176)
(32, 256, 176) (34, 256, 176)
(32, 256, 176) (40, 256, 176)
(32, 256, 176) (32, 256, 176)
[0.257

[0.282895075254972, 0.7062168232949196]
(33, 256, 176) (26, 256, 176)
(33, 256, 176) (28, 256, 176)
(33, 256, 176) (36, 256, 176)
(33, 256, 176) (33, 256, 176)
[0.23631031598874797, 0.6455494316586928]
(33, 256, 176) (33, 256, 176)
[0.04785741763651786, 0.4427493709793243]
(33, 256, 176) (33, 256, 176)
[0.3190791416527754, 0.4307755741419383]
(33, 256, 176) (34, 256, 176)
(33, 256, 176) (34, 256, 176)
(33, 256, 176) (32, 256, 176)
(33, 256, 176) (33, 256, 176)
(33, 256, 176) (30, 256, 176)
(33, 256, 176) (32, 256, 176)
(33, 256, 176) (24, 256, 176)
(33, 256, 176) (38, 256, 176)
(33, 256, 176) (32, 256, 176)
(33, 256, 176) (24, 256, 176)
(33, 256, 176) (38, 256, 176)
(33, 256, 176) (31, 256, 176)
(33, 256, 176) (32, 256, 176)
(33, 256, 176) (35, 256, 176)
(33, 256, 176) (27, 256, 176)
(33, 256, 176) (24, 256, 176)
(33, 256, 176) (32, 256, 176)
(33, 256, 176) (32, 256, 176)
(33, 256, 176) (25, 256, 176)
(33, 256, 176) (23, 256, 176)
(33, 256, 176) (27, 256, 176)
(33, 256, 176) (36, 256, 

[0.24350282394160894, 0.5377595235061027]
(32, 256, 176) (36, 256, 176)
(32, 256, 176) (29, 256, 176)
(32, 256, 176) (26, 256, 176)
(32, 256, 176) (35, 256, 176)
(32, 256, 176) (33, 256, 176)
(32, 256, 176) (39, 256, 176)
(32, 256, 176) (34, 256, 176)
(32, 256, 176) (31, 256, 176)
(32, 256, 176) (26, 256, 176)
(32, 256, 176) (32, 256, 176)
[0.35954749775266626, 0.6194041922622993]
(32, 256, 176) (28, 256, 176)
(32, 256, 176) (29, 256, 176)
(32, 256, 176) (30, 256, 176)
(32, 256, 176) (38, 256, 176)
(32, 256, 176) (29, 256, 176)
(32, 256, 176) (26, 256, 176)
(32, 256, 176) (28, 256, 176)
(32, 256, 176) (33, 256, 176)
(32, 256, 176) (29, 256, 176)
(32, 256, 176) (34, 256, 176)
(32, 256, 176) (32, 256, 176)
[0.4231121427757391, 0.4426257234775709]
(32, 256, 176) (24, 256, 176)
(32, 256, 176) (25, 256, 176)
(32, 256, 176) (27, 256, 176)
(32, 256, 176) (39, 256, 176)
(32, 256, 176) (26, 256, 176)
(32, 256, 176) (35, 256, 176)
(32, 256, 176) (25, 256, 176)
(32, 256, 176) (29, 256, 176)
(32, 

[0.2702487772904193, 0.5294078287987263]
(38, 256, 176) (30, 256, 176)
(38, 256, 176) (32, 256, 176)
(38, 256, 176) (31, 256, 176)
(38, 256, 176) (33, 256, 176)
(38, 256, 176) (27, 256, 176)
(38, 256, 176) (26, 256, 176)
(38, 256, 176) (29, 256, 176)
(38, 256, 176) (37, 256, 176)
(38, 256, 176) (40, 256, 176)
(38, 256, 176) (34, 256, 176)
(38, 256, 176) (40, 256, 176)
(38, 256, 176) (32, 256, 176)
(38, 256, 176) (33, 256, 176)
(38, 256, 176) (34, 256, 176)
(38, 256, 176) (23, 256, 176)
(38, 256, 176) (30, 256, 176)
(38, 256, 176) (26, 256, 176)
(38, 256, 176) (26, 256, 176)
(38, 256, 176) (32, 256, 176)
(38, 256, 176) (36, 256, 176)
(38, 256, 176) (29, 256, 176)
(38, 256, 176) (26, 256, 176)
(38, 256, 176) (35, 256, 176)
(38, 256, 176) (33, 256, 176)
(38, 256, 176) (39, 256, 176)
(38, 256, 176) (34, 256, 176)
(38, 256, 176) (31, 256, 176)
(38, 256, 176) (26, 256, 176)
(38, 256, 176) (32, 256, 176)
(38, 256, 176) (28, 256, 176)
(38, 256, 176) (29, 256, 176)
(38, 256, 176) (30, 256, 176)

[0.37148430948092825, 0.7324467591735794]
(32, 256, 176) (34, 256, 176)
(32, 256, 176) (26, 256, 176)
(32, 256, 176) (30, 256, 176)
(32, 256, 176) (31, 256, 176)
(32, 256, 176) (32, 256, 176)
[0.2388591791100551, 0.5583464044501848]
(32, 256, 176) (27, 256, 176)
(32, 256, 176) (31, 256, 176)
(32, 256, 176) (33, 256, 176)
(32, 256, 176) (31, 256, 176)
(32, 256, 176) (32, 256, 176)
[0.41115404119382687, 0.6281626374968948]
(32, 256, 176) (35, 256, 176)
(32, 256, 176) (25, 256, 176)
(24, 256, 176) (29, 256, 176)
(24, 256, 176) (31, 256, 176)
(24, 256, 176) (32, 256, 176)
(24, 256, 176) (26, 256, 176)
(24, 256, 176) (33, 256, 176)
(24, 256, 176) (33, 256, 176)
(24, 256, 176) (42, 256, 176)
(24, 256, 176) (28, 256, 176)
(24, 256, 176) (30, 256, 176)
(24, 256, 176) (26, 256, 176)
(24, 256, 176) (37, 256, 176)
(24, 256, 176) (24, 256, 176)
[0.1010736188567974, 0.4501965990456518]
(24, 256, 176) (40, 256, 176)
(24, 256, 176) (28, 256, 176)
(24, 256, 176) (30, 256, 176)
(24, 256, 176) (39, 256,

[0.09603033314234181, 0.49978147739055534]
(38, 256, 176) (36, 256, 176)
(38, 256, 176) (27, 256, 176)
(38, 256, 176) (30, 256, 176)
(38, 256, 176) (32, 256, 176)
(38, 256, 176) (35, 256, 176)
(38, 256, 176) (39, 256, 176)
(38, 256, 176) (38, 256, 176)
[0.2178864325451265, 0.5548860162664875]
(38, 256, 176) (31, 256, 176)
(38, 256, 176) (30, 256, 176)
(38, 256, 176) (29, 256, 176)
(38, 256, 176) (39, 256, 176)
(38, 256, 176) (28, 256, 176)
(38, 256, 176) (33, 256, 176)
(38, 256, 176) (26, 256, 176)
(38, 256, 176) (28, 256, 176)
(38, 256, 176) (36, 256, 176)
(38, 256, 176) (33, 256, 176)
(38, 256, 176) (33, 256, 176)
(38, 256, 176) (33, 256, 176)
(38, 256, 176) (34, 256, 176)
(38, 256, 176) (34, 256, 176)
(38, 256, 176) (32, 256, 176)
(38, 256, 176) (33, 256, 176)
(38, 256, 176) (30, 256, 176)
(38, 256, 176) (32, 256, 176)
(38, 256, 176) (24, 256, 176)
(38, 256, 176) (38, 256, 176)
[0.3678186012153497, 0.49244318253799596]
(38, 256, 176) (32, 256, 176)
(38, 256, 176) (24, 256, 176)
(38,

[0.48831168600561187, 0.5927717916790318]
(32, 256, 176) (33, 256, 176)
(32, 256, 176) (34, 256, 176)
(32, 256, 176) (23, 256, 176)
(32, 256, 176) (30, 256, 176)
(32, 256, 176) (26, 256, 176)
(32, 256, 176) (26, 256, 176)
(32, 256, 176) (32, 256, 176)
[0.5034473754166295, 0.48526983328525397]
(32, 256, 176) (36, 256, 176)
(32, 256, 176) (29, 256, 176)
(32, 256, 176) (26, 256, 176)
(32, 256, 176) (35, 256, 176)
(32, 256, 176) (33, 256, 176)
(32, 256, 176) (39, 256, 176)
(32, 256, 176) (34, 256, 176)
(32, 256, 176) (31, 256, 176)
(32, 256, 176) (26, 256, 176)
(32, 256, 176) (32, 256, 176)
[0.40398745540325054, 0.6699931202293115]
(32, 256, 176) (28, 256, 176)
(32, 256, 176) (29, 256, 176)
(32, 256, 176) (30, 256, 176)
(32, 256, 176) (38, 256, 176)
(32, 256, 176) (29, 256, 176)
(32, 256, 176) (26, 256, 176)
(32, 256, 176) (28, 256, 176)
(32, 256, 176) (33, 256, 176)
(32, 256, 176) (29, 256, 176)
(32, 256, 176) (34, 256, 176)
(32, 256, 176) (32, 256, 176)
[0.26667220219802257, 0.4506113354

[0.37816593712633445, 0.5418345009735116]
(27, 256, 176) (34, 256, 176)
(27, 256, 176) (29, 256, 176)
(27, 256, 176) (36, 256, 176)
(27, 256, 176) (29, 256, 176)
(27, 256, 176) (32, 256, 176)
(27, 256, 176) (31, 256, 176)
(27, 256, 176) (28, 256, 176)
(27, 256, 176) (28, 256, 176)
(27, 256, 176) (34, 256, 176)
(27, 256, 176) (24, 256, 176)
(27, 256, 176) (37, 256, 176)
(27, 256, 176) (30, 256, 176)
(27, 256, 176) (32, 256, 176)
(27, 256, 176) (23, 256, 176)
(27, 256, 176) (25, 256, 176)
(27, 256, 176) (29, 256, 176)
(27, 256, 176) (31, 256, 176)
(27, 256, 176) (41, 256, 176)
(27, 256, 176) (29, 256, 176)
(27, 256, 176) (25, 256, 176)
(27, 256, 176) (28, 256, 176)
(27, 256, 176) (38, 256, 176)
(27, 256, 176) (30, 256, 176)
(27, 256, 176) (32, 256, 176)
(27, 256, 176) (31, 256, 176)
(27, 256, 176) (33, 256, 176)
(27, 256, 176) (27, 256, 176)
[0.009627636936015682, 0.34172542265888217]
(27, 256, 176) (26, 256, 176)
(27, 256, 176) (29, 256, 176)
(27, 256, 176) (37, 256, 176)
(27, 256, 176)

[0.23596870481574075, 0.6128140855210527]
(32, 256, 176) (31, 256, 176)
(32, 256, 176) (28, 256, 176)
(32, 256, 176) (28, 256, 176)
(32, 256, 176) (34, 256, 176)
(32, 256, 176) (24, 256, 176)
(32, 256, 176) (37, 256, 176)
(32, 256, 176) (30, 256, 176)
(32, 256, 176) (32, 256, 176)
[0.05781227290140525, 0.6615756795128942]
(32, 256, 176) (23, 256, 176)
(32, 256, 176) (25, 256, 176)
(32, 256, 176) (29, 256, 176)
(32, 256, 176) (31, 256, 176)
(32, 256, 176) (41, 256, 176)
(32, 256, 176) (29, 256, 176)
(32, 256, 176) (25, 256, 176)
(32, 256, 176) (28, 256, 176)
(32, 256, 176) (38, 256, 176)
(32, 256, 176) (30, 256, 176)
(32, 256, 176) (32, 256, 176)
[0.07448481306594051, 0.5665960196876192]
(32, 256, 176) (31, 256, 176)
(32, 256, 176) (33, 256, 176)
(32, 256, 176) (27, 256, 176)
(32, 256, 176) (26, 256, 176)
(32, 256, 176) (29, 256, 176)
(32, 256, 176) (37, 256, 176)
(32, 256, 176) (40, 256, 176)
(32, 256, 176) (34, 256, 176)
(32, 256, 176) (40, 256, 176)
(32, 256, 176) (32, 256, 176)
[0.2

[0.2675745187847647, 0.5916882426694967]
(32, 256, 176) (24, 256, 176)
(32, 256, 176) (38, 256, 176)
(32, 256, 176) (32, 256, 176)
[0.16417058373347687, 0.5831260985176311]
(32, 256, 176) (24, 256, 176)
(32, 256, 176) (38, 256, 176)
(32, 256, 176) (31, 256, 176)
(32, 256, 176) (32, 256, 176)
[0.4111885625554197, 0.49788192309801593]
(32, 256, 176) (35, 256, 176)
(32, 256, 176) (27, 256, 176)
(32, 256, 176) (24, 256, 176)
(32, 256, 176) (32, 256, 176)
[0.205580337490193, 0.581266132059547]
(32, 256, 176) (32, 256, 176)
(32, 256, 176) (25, 256, 176)
(32, 256, 176) (23, 256, 176)
(32, 256, 176) (27, 256, 176)
(32, 256, 176) (36, 256, 176)
(32, 256, 176) (32, 256, 176)
[0.24439252232628494, 0.6023831665196657]
(32, 256, 176) (34, 256, 176)
(32, 256, 176) (26, 256, 176)
(32, 256, 176) (30, 256, 176)
(32, 256, 176) (31, 256, 176)
(32, 256, 176) (32, 256, 176)
[0.3376613700745512, 0.5912396774770758]
(32, 256, 176) (27, 256, 176)
(32, 256, 176) (31, 256, 176)
(32, 256, 176) (33, 256, 176)
(32

[0.16445721549590048, 0.46284461445563757]
(27, 256, 176) (34, 256, 176)
(27, 256, 176) (28, 256, 176)
(27, 256, 176) (36, 256, 176)
(27, 256, 176) (32, 256, 176)
(27, 256, 176) (31, 256, 176)
(27, 256, 176) (27, 256, 176)
[0.24430499765711347, 0.5189411693650571]
(27, 256, 176) (34, 256, 176)
(27, 256, 176) (29, 256, 176)
(27, 256, 176) (36, 256, 176)
(27, 256, 176) (29, 256, 176)
(27, 256, 176) (32, 256, 176)
(27, 256, 176) (31, 256, 176)
(27, 256, 176) (28, 256, 176)
(27, 256, 176) (28, 256, 176)
(27, 256, 176) (34, 256, 176)
(27, 256, 176) (24, 256, 176)
(27, 256, 176) (37, 256, 176)
(27, 256, 176) (30, 256, 176)
(27, 256, 176) (32, 256, 176)
(27, 256, 176) (23, 256, 176)
(27, 256, 176) (25, 256, 176)
(27, 256, 176) (29, 256, 176)
(27, 256, 176) (31, 256, 176)
(27, 256, 176) (41, 256, 176)
(27, 256, 176) (29, 256, 176)
(27, 256, 176) (25, 256, 176)
(27, 256, 176) (28, 256, 176)
(27, 256, 176) (38, 256, 176)
(27, 256, 176) (30, 256, 176)
(27, 256, 176) (32, 256, 176)
(27, 256, 176) 

[0.29647835439120795, 0.4054057594113137]
(32, 256, 176) (26, 256, 176)
(32, 256, 176) (33, 256, 176)
(32, 256, 176) (33, 256, 176)
(32, 256, 176) (42, 256, 176)
(32, 256, 176) (28, 256, 176)
(32, 256, 176) (30, 256, 176)
(32, 256, 176) (26, 256, 176)
(32, 256, 176) (37, 256, 176)
(32, 256, 176) (24, 256, 176)
(32, 256, 176) (40, 256, 176)
(32, 256, 176) (28, 256, 176)
(32, 256, 176) (30, 256, 176)
(32, 256, 176) (39, 256, 176)
(32, 256, 176) (27, 256, 176)
(32, 256, 176) (34, 256, 176)
(32, 256, 176) (28, 256, 176)
(32, 256, 176) (36, 256, 176)
(32, 256, 176) (32, 256, 176)
[0.09555828476396015, 0.43375381819676273]
(32, 256, 176) (31, 256, 176)
(32, 256, 176) (27, 256, 176)
(32, 256, 176) (34, 256, 176)
(32, 256, 176) (29, 256, 176)
(32, 256, 176) (36, 256, 176)
(32, 256, 176) (29, 256, 176)
(32, 256, 176) (32, 256, 176)
[0.390912482582729, 0.6137681992983507]
(32, 256, 176) (31, 256, 176)
(32, 256, 176) (28, 256, 176)
(32, 256, 176) (28, 256, 176)
(32, 256, 176) (34, 256, 176)
(32, 

(34, 256, 176) (29, 256, 176)
(34, 256, 176) (38, 256, 176)
(34, 256, 176) (36, 256, 176)
(34, 256, 176) (27, 256, 176)
(34, 256, 176) (30, 256, 176)
(34, 256, 176) (32, 256, 176)
(34, 256, 176) (35, 256, 176)
(34, 256, 176) (39, 256, 176)
(34, 256, 176) (38, 256, 176)
(34, 256, 176) (31, 256, 176)
(34, 256, 176) (30, 256, 176)
(34, 256, 176) (29, 256, 176)
(34, 256, 176) (39, 256, 176)
(34, 256, 176) (28, 256, 176)
(34, 256, 176) (33, 256, 176)
(34, 256, 176) (26, 256, 176)
(34, 256, 176) (28, 256, 176)
(34, 256, 176) (36, 256, 176)
(34, 256, 176) (33, 256, 176)
(34, 256, 176) (33, 256, 176)
(34, 256, 176) (33, 256, 176)
(34, 256, 176) (34, 256, 176)
[0.10990787872448118, 0.5617510108371966]
(34, 256, 176) (34, 256, 176)
[0.12793852972681732, 0.5492828046401397]
(34, 256, 176) (32, 256, 176)
(34, 256, 176) (33, 256, 176)
(34, 256, 176) (30, 256, 176)
(34, 256, 176) (32, 256, 176)
(34, 256, 176) (24, 256, 176)
(34, 256, 176) (38, 256, 176)
(34, 256, 176) (32, 256, 176)
(34, 256, 176) (

[0.3135536406993162, 0.6997114439833588]
(30, 256, 176) (32, 256, 176)
(30, 256, 176) (31, 256, 176)
(30, 256, 176) (33, 256, 176)
(30, 256, 176) (27, 256, 176)
(30, 256, 176) (26, 256, 176)
(30, 256, 176) (29, 256, 176)
(30, 256, 176) (37, 256, 176)
(30, 256, 176) (40, 256, 176)
(30, 256, 176) (34, 256, 176)
(30, 256, 176) (40, 256, 176)
(30, 256, 176) (32, 256, 176)
(30, 256, 176) (33, 256, 176)
(30, 256, 176) (34, 256, 176)
(30, 256, 176) (23, 256, 176)
(30, 256, 176) (30, 256, 176)
[0.20676532660272026, 0.4591167724338711]
(30, 256, 176) (26, 256, 176)
(30, 256, 176) (26, 256, 176)
(30, 256, 176) (32, 256, 176)
(30, 256, 176) (36, 256, 176)
(30, 256, 176) (29, 256, 176)
(30, 256, 176) (26, 256, 176)
(30, 256, 176) (35, 256, 176)
(30, 256, 176) (33, 256, 176)
(30, 256, 176) (39, 256, 176)
(30, 256, 176) (34, 256, 176)
(30, 256, 176) (31, 256, 176)
(30, 256, 176) (26, 256, 176)
(30, 256, 176) (32, 256, 176)
(30, 256, 176) (28, 256, 176)
(30, 256, 176) (29, 256, 176)
(30, 256, 176) (3

[0.15807415635530886, 0.5230097573403084]
(31, 256, 176) (33, 256, 176)
(31, 256, 176) (31, 256, 176)
[0.1704293402628749, 0.6767558955563369]
(31, 256, 176) (32, 256, 176)
(31, 256, 176) (35, 256, 176)
(31, 256, 176) (25, 256, 176)
(32, 256, 176) (29, 256, 176)
(32, 256, 176) (31, 256, 176)
(32, 256, 176) (32, 256, 176)
[0.3421400973958075, 0.31230118173624605]
(32, 256, 176) (26, 256, 176)
(32, 256, 176) (33, 256, 176)
(32, 256, 176) (33, 256, 176)
(32, 256, 176) (42, 256, 176)
(32, 256, 176) (28, 256, 176)
(32, 256, 176) (30, 256, 176)
(32, 256, 176) (26, 256, 176)
(32, 256, 176) (37, 256, 176)
(32, 256, 176) (24, 256, 176)
(32, 256, 176) (40, 256, 176)
(32, 256, 176) (28, 256, 176)
(32, 256, 176) (30, 256, 176)
(32, 256, 176) (39, 256, 176)
(32, 256, 176) (27, 256, 176)
(32, 256, 176) (34, 256, 176)
(32, 256, 176) (28, 256, 176)
(32, 256, 176) (36, 256, 176)
(32, 256, 176) (32, 256, 176)
[0.15358678580147192, 0.35062903355614694]
(32, 256, 176) (31, 256, 176)
(32, 256, 176) (27, 25

(27, 256, 176) (32, 256, 176)
(27, 256, 176) (25, 256, 176)
(27, 256, 176) (23, 256, 176)
(27, 256, 176) (27, 256, 176)
[0.025708501764083992, 0.2554482729165136]
(27, 256, 176) (36, 256, 176)
(27, 256, 176) (32, 256, 176)
(27, 256, 176) (34, 256, 176)
(27, 256, 176) (26, 256, 176)
(27, 256, 176) (30, 256, 176)
(27, 256, 176) (31, 256, 176)
(27, 256, 176) (32, 256, 176)
(27, 256, 176) (27, 256, 176)
(27, 256, 176) (31, 256, 176)
(27, 256, 176) (33, 256, 176)
(27, 256, 176) (31, 256, 176)
(27, 256, 176) (32, 256, 176)
(27, 256, 176) (35, 256, 176)
(27, 256, 176) (25, 256, 176)
(31, 256, 176) (29, 256, 176)
(31, 256, 176) (31, 256, 176)
[0.28394034648006444, 0.46976652523187573]
(31, 256, 176) (32, 256, 176)
(31, 256, 176) (26, 256, 176)
(31, 256, 176) (33, 256, 176)
(31, 256, 176) (33, 256, 176)
(31, 256, 176) (42, 256, 176)
(31, 256, 176) (28, 256, 176)
(31, 256, 176) (30, 256, 176)
(31, 256, 176) (26, 256, 176)
(31, 256, 176) (37, 256, 176)
(31, 256, 176) (24, 256, 176)
(31, 256, 176)

[0.02707065672997233, 0.367408856648132]
(33, 256, 176) (29, 256, 176)
(33, 256, 176) (34, 256, 176)
(33, 256, 176) (32, 256, 176)
(33, 256, 176) (24, 256, 176)
(33, 256, 176) (25, 256, 176)
(33, 256, 176) (27, 256, 176)
(33, 256, 176) (39, 256, 176)
(33, 256, 176) (26, 256, 176)
(33, 256, 176) (35, 256, 176)
(33, 256, 176) (25, 256, 176)
(33, 256, 176) (29, 256, 176)
(33, 256, 176) (35, 256, 176)
(33, 256, 176) (31, 256, 176)
(33, 256, 176) (32, 256, 176)
(33, 256, 176) (34, 256, 176)
(33, 256, 176) (32, 256, 176)
(33, 256, 176) (32, 256, 176)
(33, 256, 176) (27, 256, 176)
(33, 256, 176) (27, 256, 176)
(33, 256, 176) (29, 256, 176)
(33, 256, 176) (38, 256, 176)
(33, 256, 176) (36, 256, 176)
(33, 256, 176) (27, 256, 176)
(33, 256, 176) (30, 256, 176)
(33, 256, 176) (32, 256, 176)
(33, 256, 176) (35, 256, 176)
(33, 256, 176) (39, 256, 176)
(33, 256, 176) (38, 256, 176)
(33, 256, 176) (31, 256, 176)
(33, 256, 176) (30, 256, 176)
(33, 256, 176) (29, 256, 176)
(33, 256, 176) (39, 256, 176)

[0.20253308914295948, 0.43443951750419874]
(32, 256, 176) (31, 256, 176)
(32, 256, 176) (33, 256, 176)
(32, 256, 176) (27, 256, 176)
(32, 256, 176) (26, 256, 176)
(32, 256, 176) (29, 256, 176)
(32, 256, 176) (37, 256, 176)
(32, 256, 176) (40, 256, 176)
(32, 256, 176) (34, 256, 176)
(32, 256, 176) (40, 256, 176)
(32, 256, 176) (32, 256, 176)
[0.41808501543520993, 0.567678911668402]
(32, 256, 176) (33, 256, 176)
(32, 256, 176) (34, 256, 176)
(32, 256, 176) (23, 256, 176)
(32, 256, 176) (30, 256, 176)
(32, 256, 176) (26, 256, 176)
(32, 256, 176) (26, 256, 176)
(32, 256, 176) (32, 256, 176)
[0.3252371503948861, 0.6091337578865654]
(32, 256, 176) (36, 256, 176)
(32, 256, 176) (29, 256, 176)
(32, 256, 176) (26, 256, 176)
(32, 256, 176) (35, 256, 176)
(32, 256, 176) (33, 256, 176)
(32, 256, 176) (39, 256, 176)
(32, 256, 176) (34, 256, 176)
(32, 256, 176) (31, 256, 176)
(32, 256, 176) (26, 256, 176)
(32, 256, 176) (32, 256, 176)
[0.3390385398299273, 0.526542690784741]
(32, 256, 176) (28, 256, 

[0.1557296154204415, 0.352668238759877]
(25, 256, 176) (29, 256, 176)
(25, 256, 176) (31, 256, 176)
(25, 256, 176) (41, 256, 176)
(25, 256, 176) (29, 256, 176)
(25, 256, 176) (25, 256, 176)
[0.19181467082720888, 0.5601241636101669]
(25, 256, 176) (28, 256, 176)
(25, 256, 176) (38, 256, 176)
(25, 256, 176) (30, 256, 176)
(25, 256, 176) (32, 256, 176)
(25, 256, 176) (31, 256, 176)
(25, 256, 176) (33, 256, 176)
(25, 256, 176) (27, 256, 176)
(25, 256, 176) (26, 256, 176)
(25, 256, 176) (29, 256, 176)
(25, 256, 176) (37, 256, 176)
(25, 256, 176) (40, 256, 176)
(25, 256, 176) (34, 256, 176)
(25, 256, 176) (40, 256, 176)
(25, 256, 176) (32, 256, 176)
(25, 256, 176) (33, 256, 176)
(25, 256, 176) (34, 256, 176)
(25, 256, 176) (23, 256, 176)
(25, 256, 176) (30, 256, 176)
(25, 256, 176) (26, 256, 176)
(25, 256, 176) (26, 256, 176)
(25, 256, 176) (32, 256, 176)
(25, 256, 176) (36, 256, 176)
(25, 256, 176) (29, 256, 176)
(25, 256, 176) (26, 256, 176)
(25, 256, 176) (35, 256, 176)
(25, 256, 176) (33