In [17]:
import numpy as np

In [46]:
import glob
paths = glob.glob("/home/abhijit/nas_drive/Data_WholeBody/NAKO/NAKO_200/MRI/*")
x = []
for p in paths:
    x.append(p.split('/')[-1])

print(x)

['100000', '100001', '100002', '100003', '100004', '100005', '100006', '100007', '100008', '100009', '100010', '100011', '100012', '100013', '100014', '100015', '100016', '100017', '100018', '100019', '100020', '100021', '100022', '100023', '100024', '100025', '100026', '100027', '100028', '100029', '100030', '100031', '100032', '100033', '100034', '100035', '100036', '100037', '100038', '100039', '100040', '100041', '100042', '100043', '100044', '100045', '100046', '100047', '100048', '100049', '100050', '100051', '100052', '100053', '100054', '100055', '100056', '100057', '100058', '100059', '100060', '100061', '100062', '100063', '100064', '100065', '100066', '100067', '100068', '100069', '100070', '100071', '100072', '100073', '100074', '100075', '100076', '100077', '100078', '100079', '100080', '100081', '100082', '100083', '100084', '100085', '100086', '100087', '100088', '100089', '100090', '100091', '100092', '100093', '100094', '100095', '100096', '100097', '100098', '100099',

In [36]:
x = np.zeros((3, 2))
x.shape

(3, 2)

In [41]:
x[0] = (1,2)
x[1] = (2,3)
x[2] = (4,5)

In [45]:
np.mean(x[:, 1])

3.3333333333333335

In [16]:
y = (x == 11).astype(np.float)
y

z = np.max(np.max(x, 0),1)
z

array([11, 55, 33])

In [47]:
y = np.roll(x, 1, axis=1)
y

array([[[ 8,  9, 10, 11],
        [ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[20, 21, 22, 23],
        [12, 13, 14, 15],
        [16, 17, 18, 19]]])

In [23]:
y = np.transpose(x, [2,1,0])


In [27]:
print(x,'\n'*5, y)

[[[1]
  [2]
  [3]]

 [[4]
  [5]
  [6]]] 




 [[[1 4]
  [2 5]
  [3 6]]]


In [28]:
z = np.transpose(y, [2,1,0])

In [29]:
z

array([[[1],
        [2],
        [3]],

       [[4],
        [5],
        [6]]])